### ISSUE TITLE
گرفتن اطلاعات سهام داران به زبان سی شارپ

### ISSUE THREAD

**Issue by Mortezakhataei** [Glyphack/pytse-client#103]
با سلام و خسته نباشی
من یک برنامه وینقرم با زیان **سی شارپ** توشتم میخاهم اطلاعات سهامدارن دریافت کنم 
لطفا راهنمائی کنید چطور مثلا سهامداران سهام برکت دریافت کنم
با تشکر فراوان

**Comment by Glyphack** [comment]
سلام این پروژه با پایتون نوشته شده درباره کد سی شارپ نظری ندارم ولی توی داکیومنت این پروژه روش این کار باپایتون گفته شده
