### ISSUE TITLE
تبدیل کل پروژه به فایل اجرایی

### ISSUE THREAD

**Issue by Mortezakhataei** [Glyphack/pytse-client#104]
سلام 
 exe من اگر بخواهم کل پروژه به  
تبدیل کنم کدام فایل باید انتخاب کنم و چگونه پارامتر بدهم 
با تشکر فراوان

**Comment by Glyphack** [comment]
سلام این کار قابل انجام نیست این پروژه کتابخونه هست و کاری انجام نمیده که به فایل اجرایی تبدیل بشه
