### ISSUE TITLE
از کار افتادن سایت

### ISSUE THREAD

**Issue by EMPS1** [Glyphack/pytse-client#105]
سلام خسته نباشید. گویا چندروزی هست که سایت کلا از دسترس خارج شده و ارور تایم اوت میده 

tsetmc.com port 80: Connection timed out

پس از بررسی هایی که انجام دادم متوجه شدم گویا سایت آی پی های غیرایرانی رو اینطوری میکنه و اجازه ارتباط نمیده
برای مثال اگر با فیلترشکن وارد سایت تسه بشید میبینید که عملا لود نمیشه

الان من مشکلم اینکه دیتارو نمیتونم بگیرم. شماهم همچین مشکلی دارید یا شاید سیستم من ایراد داره؟ البته وقتی پروکسی ست میکنم درست میشه! پروکسی هم البته باید ایرانی باشه...
کسی همچین مشکلی داشته؟ راه حل؟

**Comment by Glyphack** [comment]
آره بنظر میاد فقط با آیپی ایرانی میشه وارد شد پروکسی ایرانی از کجا میشه گرفت؟

**Comment by EMPS1** [comment]
سلام گویا مشکل الان حل شده.
پروکسی ایرانی رو من از سایتهای پروکسی پیدا میکنم
توی گوگل بزنید 
proxy iran list
بعد چنتا سایت میاره که من از سایت زیر میگرفتم
spys.one/free-proxy-list/IR

بنظر میاد باید اماده هرگونه سناریو ای باشیم! یه سایت با کدنویسی مسخره بالا آواردن همچیشو هم عین دزد مخفی میکنن یا یه تیکه از دیتارو توی صفحه جاسازی کردن یه تیکه دیگشو باید از لینک مربوطه بگیری فازشونو معلوم نیست. اینم که از وضعیت سایته که رنج آیپی های خارجی رو مسدود میکنه

اینهمه سایت خارجی هست که ملیون ها کاربر داره خیلی شیک مجلسی هم کدنویسی کردن و مشکل کمبود سرعت هم حس نمیشه
اینا یا بخاطر اینکه سرعت لود بره بالا اینطوری  غیراستاندارد کدنویسی کردن یا از همون اول دیوار رو کج نهادن و تا ثریا کج بالا رفته یاهم میخان مثلا مخفی بازی در بیارن

اگه بخاطر سرعته که جونشون در بیاد هزینه سرور کنن بالاخره یک سایت دولتی پربازدید هست نباید حداقل یک دیتاسنتر پرسرعت ساپورتش کنه؟؟ اگرم بخاطر مخفی کردنه که هیجوره نمیشه چیزیو مخفی کرد. الان خودشون ضرر کردن که غیراستاندارد کدنویسی کردن و الان دیگه اونقد حجم کدنویسی سایت بالاست که نمیتونن تغییرش بدن یا تغییرش ماه ها زمان میبره
چون هر نوع دیتایی رو میشه از سایت گرفت ! حتی من با پی اچ پی هم هر نوع دیتایی رو میتونم بگیرم

 خلاصه فاز کدنویسی سایت معلوم نیست چیه

حالا باز امروز درست شده اما خب اینطور که مشخصه اگر بخان میتونن آیپی هارو ببندن. بنظر باید برای این مشکل یک فکر اساسی کرد.

**Comment by Glyphack** [comment]
سایت دوباره کار میکنه
