### ISSUE TITLE
امکان NAV ابطال صندوق و زمان آن لحظه ای

### ISSUE THREAD

**Issue by amirhooshangemamjomeh** [Glyphack/pytse-client#108]
<p dir="rtl">
`با سلام
در صورت امکان قسمت ارزش NAV ابطال  و زمان اعلام آن را در صندوق ها را اضافه کنید . 

این داده ها اطلاعات مفیدی رو برای بدست آوردن ارزش واقعی یک صندوق میده . 

**راه حل**
 متونیم اطلاعات رو از این قسمت بدست بیاریم 
بفرض مثال سهم [دارا یکم](http://www.tsetmc.com/Loader.aspx?ParTree=151311&i=62235397452612911) که یک صندوق است این گزینه رو  دارد 

![nav](https://user-images.githubusercontent.com/30677591/128673883-d4b84e3b-eec3-4085-8522-6fba5d83dfce.png)

</p>

**Comment by Glyphack** [comment]
ممنون میشه این با یه فلش یا علامتی نشون بدی که از کجا این پنجره باز میشه؟

**Comment by abcdamir2** [comment]
سلام به فقط مخصوص صندوق ها است .
