### ISSUE TITLE
امکان دریافت ریز معاملات نماد در روز جازی و به صورت تاریخی (tick tables)

### ISSUE THREAD

**Issue by A5DkjGQUZx** [Glyphack/pytse-client#109]
<p dir="rtl">

**مشکلی که دارید چی هست؟**
ظاهراً امکان دریافت tick table وجود ندارد و فقط OHLCV ها را میتوان دریافت کرد!

**راه حل**
مثلاً در اینجا در بخش سوابق نماد بانک دی در تب معاملات تیک های ی تاریخ بخصوص رو داریم...
http://cdn.tsetmc.com/History/44818950263583523/20210814

**نکات تکمیلی**
تیک های روز جاری هم در صفحه خود نماد بخش ریز معاملات قابل دسترسی هست...
مزیت دسترسی به تیک ها این هست که فرد میتونه خودش کندلهای OHLCV با time frame دلخواه بسازه. مثلاً من دوست دارم بازار رو به صورت هفت کندل 30 دقیقه ای پایش کنم....
</p>
![image](https://user-images.githubusercontent.com/25065763/129476039-c99f473b-9caa-43ec-b3f0-f85e456711a7.png)
![image](https://user-images.githubusercontent.com/25065763/129476061-508a77e2-6fe7-4fff-b5c4-1a8df1ce4ac4.png)

**Comment by sfmqrb** [comment]
تیک دیتای روز معاملاتی اخیر هست الان
برای تاریخی هم ایده خوبیه
@A5DkjGQUZx

**Comment by Glyphack** [comment]
اینجا اضافه شده آپدیت کنید و استفاده کنید:
https://github.com/Glyphack/pytse-client#%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF-%D8%AA%D8%A7%D8%B1%DB%8C%D8%AE%DA%86%D9%87-%D8%AC%D8%B2%D8%A6%DB%8C%D8%A7%D8%AA-%D9%85%D8%B9%D8%A7%D9%85%D9%84%D8%A7%D8%AA
