### ISSUE TITLE
عدم نمایش اسم کامل

### ISSUE THREAD

**Issue by mostafa2msh** [Glyphack/pytse-client#111]
سلام برای نمادهای اختیار معامله مثل ضخود7077 وقتی دستور زیر رو بزنیم:
ticker = tse.Ticker("ضخود7077")
print(ticker.title) 
فقط نشون داده میشه:
اختيارخ خودرو
درصورتی که اسم کاملش هست:
اختيارخ خودرو-3000-1400/07/07
بقیه اسمش شامل اطلاعات مهمی هست
راهی وجود داره که بشه بقیه اسمش هم دریافت کرد؟

**Comment by Glyphack** [comment]
آره فکر کنم ما اسم رو فقط بخش اول رو سلکت میکنیم برای این باید یه چیزی مثل اسم کامل اضافه بشه ممنون.

**Comment by mostafa2msh** [comment]
سلام و تشکر. نمادهای اختیار معامله رو کی درست میکنید؟
مثل ضخود1053

**Comment by Glyphack** [comment]
سلام این به مستر اضافه شده ولی هنوز ریلیز نشده توی ورژن بعدی یعنی 0.11.0  قرار میگیره
میشه تا اون موقع خود برنچ رو نصب کنید
```
pip install git+https://github.com/Glyphack/pytse-client.git
```

**Comment by mostafa2msh** [comment]
سلام آدرسی که دادید خطا میده . ممنون میشم بررسی کنید. ضمنا ورژن جدید کی منتشر میشه؟

 ERROR: Error [WinError 2] The system cannot find the file specified while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by mostafa2msh** [comment]
سلام لطفا راهنمایی کنید

**Comment by Glyphack** [comment]
سلام این ورژن رو نصب کنید تا زمانی که کامل ریلیز بشه
ریلیز بعدی بعد از اضافه کردن یه فیچر جدید انجام میشه
```
pip install pytse-client==0.11.0rc1
```

**Comment by mostafa2msh** [comment]
ممنون عالی شد

**Comment by mostafa2msh** [comment]
سلام وقتی ورژن 0.11.0rc1 رو نصب میکنم و نام کامل یک نماد رو فراخوانی میکنم این خطا رو بهم میده:
AttributeError: module 'functools' has no attribute 'cached_property'

**Comment by mostafa2msh** [comment]
سلام ممنون میشم راهنمایی کنید  @Glyphack @alised

**Comment by alised** [comment]
سلام
نسخه پایتون باید ۳.۸ به بالا باشه.  و این دستور هم اجرا کنید pip uninstall functools
اگر مشکلتان رفع نشد لطفا یک ایشو جدید ایجاد کنید و تمامی سوالات را تکمیل کنید تا بررسی شود.

**Comment by mostafa2msh** [comment]
با تشکر مشکل از  پایین بودن نسخه پایتون بود مرسی
