### ISSUE TITLE
اضافه کردن دریافت سابقه معاملاتی در تایم فریم های دقیقه ای 

### ISSUE THREAD

**Issue by smmss** [Glyphack/pytse-client#113]
<p dir="rtl">

**مشکلی که دارید چی هست؟**
عدم دریافت سابقه معاملاتی بصورت تایم فریم های دقیقه ای

**راه حل**
 کراول کردن دیتا از سایت زیر، برای مثال
 http://cdn.tsetmc.com/History/65883838195688438/20110810

**نکات تکمیلی**

</p>

**Comment by sfmqrb** [comment]
چیزی که از تایم فریم دقیقه ای کامل تره دیتای intra-day tick هست.
http://cdn.tsetmc.com/api/Trade/GetTradeHistory/19040514831923530/20220410/true
در url بالا همون طور که می بینید دیتای تیک به صورت تاریخی برای سهمی با آي‌دی 19040514831923530 در روز 20220410 گرفته شده.

**Comment by Glyphack** [comment]
این  اضافه شده آپدیت کنید و این بخش رو بخونید:
https://github.com/Glyphack/pytse-client#%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF-%D8%AA%D8%A7%D8%B1%DB%8C%D8%AE%DA%86%D9%87-%D8%AC%D8%B2%D8%A6%DB%8C%D8%A7%D8%AA-%D9%85%D8%B9%D8%A7%D9%85%D9%84%D8%A7%D8%AA
