### ISSUE TITLE
گزارش مشکل

### ISSUE THREAD

**Issue by h0ssein2011** [Glyphack/pytse-client#12]
بعضی از سهام رو وقتی که سرچ میکنیم ارور میاره مثلا  تملت ُ یا زکوثر
بنظرم بخاطر حروف فارسی هستش و اگه مثل پکیج 
theran_stock
اگه بشه که بر اساس ادرس پیج سهم در سایت بورس و یا  گزینه لایک ...سهم رو سرچ کرد خیلی خوب میشه 

پایتون ۳.۷ در ابونتو دارم استفاده میکنم 
اسکرین شات رو اضافه کردم که ببینید 
![image](https://user-images.githubusercontent.com/11961586/86320697-a5989c80-bc4c-11ea-98f0-495d19ca771e.png)

**Comment by Glyphack** [comment]
<div dir="rtl">
سلام،

 این مشکل به خاطر این هست که پکیج سهام تملت رو نداره، سهام‌های جدید باید اضافه بشن.
فکر میکنم اینکه دسترسی به سهم‌ها با ادرس هم انجام بشه چیز بدی نباشه ولی کاربردش فقط زمانیه که پکیج یه سهم رو نداشته باشه و لازم بشه با ادرس به اون دسترسی داشت، توی این حالت اینکه سهام به پکیج اضافه بشه شاید بهتر باشه. این نیاز به فکر بیشتری داره واسه راه حل.
</div>

**Comment by h0ssein2011** [comment]
ممنون 
باز هم خیلی کار راه اندازه پکیجتون و بهم کمک کرد اسکریپتی بنویسم که سهمهای مورد نظرم رو تحلیل کنم 
بنظرتون چقدر طول میکشه
 کل سهام به پکیج اضافه بشن ؟
ممنون

**Comment by Glyphack** [comment]
الان تعداد زیادی از سهام‌ها توی پکیج هست و امروز یا فردا یه تعداد دیگه قراره اضافه بشه. باز هم برای اینکه کامل بشه خوبه هرجا نقصی بود بگید.

**Comment by Glyphack** [comment]
این مشکل توی این پول ریکوعست https://github.com/Glyphack/pytse-client/pull/14 حل شده.
ازین به بعد سهام هایی که اسمشون توی لیست نباشه دیتاشون از سایت گرفته میشه.

**Comment by h0ssein2011** [comment]
من پکیج رو اپدیت کردم ولی هنوز ارور میگیرم روی نمادهایی که تو لیست نیستن 
جایی در استایل کد تغییر ایجاد شده؟

import pytse_client as tse
import pandas as pd
tickers = tse.download(symbols='تملت', write_to_csv=True)
tickers = tickers['تملت'] 

ارور زیر میاد مثل قبل
KeyError: 'تملت'

**Comment by Glyphack** [comment]
پکیج هنوز آپدیت نشده و توی ورژن بعدی خواهد اومد امروز یا فردا آپدیت جدید رو میزارم
مرسی

**Comment by h0ssein2011** [comment]
بعد از اپدیت پکیج این ارور میاد 
![image](https://user-images.githubusercontent.com/11961586/87339473-eb623880-c55b-11ea-8bae-5862fe5949d3.png)

**Comment by Glyphack** [comment]
این آخرش ارور دسترسی داده احتمالا پکیج جایی نصب شده که دسترسی یوزر بهش دسترسی نداره.
```
~>pip3 install pytse-client
~> python3
Python 3.8.3 (default, May 17 2020, 14:48:56) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytse_client as tse
>>> tse.Ticker("تملت")
<pytse_client.ticker.Ticker object at 0x7f37f5594850>
>>> t = tse.Ticker("تملت")
>>> t.history
               open     high      low  adjClose          value     volume    count    close
date                                                                                       
2020-03-04   3400.0   3400.0   3400.0    3400.0  2406375428600  707757479  1681523   3400.0
2020-03-07   3570.0   3570.0   3570.0    3570.0    54577392450   15287785     3680   3570.0
2020-03-09   3748.0   3748.0   3748.0    3748.0    99177240996   26461377     4437   3748.0
2020-03-10   3935.0   3935.0   3935.0    3935.0   280419932545   71263007     5131   3935.0
2020-03-11   4131.0   4131.0   4131.0    4131.0   138235586904   33462984     7309   4131.0
...             ...      ...      ...       ...            ...        ...      ...      ...
2020-07-07  18800.0  18850.0  17800.0   18190.0  1089068295670   59878203    28335  17840.0
2020-07-08  17800.0  18000.0  17290.0   17390.0   779225204560   44796780    19356  17290.0
2020-07-11  16530.0      0.0      0.0   16790.0   693586245970   41318546    16509  16850.0
2020-07-12  17000.0  17620.0  16030.0   17340.0   896581854560   51696344    21143  16520.0
2020-07-13  16840.0  17100.0  16480.0   16590.0   716625976490   43190537    19701  16480.0

[72 rows x 8 columns]
```

**Comment by Glyphack** [comment]
من این ایشو رو میبندم چون بنظر مشکل حل شده اگر چیزی بود بعدا میشه دوباره بازش کرد.:thumbsup:
