### ISSUE TITLE
تکمیل دیتای گذشته برخی نمادها

### ISSUE THREAD

**Issue by alised** [Glyphack/pytse-client#120]
<p dir="rtl">
روز بخیر

دیتای گذشته برخی نمادها کامل نیست دلیلش این است که اگر نمادی مثلا از فرابورس به بورس منتقل بشه یک آی دی جدید میگیره و نماد قبلی حذف میشه دیتای گذشته در حذف شده باقی میماند و به آی دی جدید منتقل نمیشود بنابراین برای این سهم ها باید تمامی آیدی های مربوطه را پیدا کنیم و تاریخچه قیمت همه را با هم ترکیب کنیم.
در وب سرویس تجاری لیست همه نمادها حتی حذف شده را میدهد ولی در نسخه رایگان اینطور نیست. در وب سایت هم جایی ندیدم لیست کامل نمادها را بدهد. اگر راه حلی برای دریافت لیست نمادهای حذف شده دارید بفرمایید.

در حال حاضر می توان با جستجوی نام یک نماد لیست نمادهای همنام را پیدا کرد و با مقایسه نام نماد آیدی نماد حذف شده مربوطه را پیدا کرد.
http://www.tsetmc.com/tsev2/data/search.aspx?skey=شمواد
 خروجی:
شمواد,توليد مواداوليه الياف مصنوعي,28251956446987982,63024594906691211,36983414883698672,46641947712792679,4,1,2,2,C1;شمواد,توليدمواداوليه الياف‌مصنوعي‌,29915504190030439,17417708613062919,68947994698969727,66530487511832946,1,0,1,1,N2;شموادح,ح . مواداوليه‌الياف‌مصنوعي‌,13279993223440273,70745819355833013,67453827703059320,29271059559720372,1,0,1,1,N2;

که ستون هشتم اگر صفر باشد به معنی نماد قدیمی حذف شده است.
با استفاده از این اطلاعات می توان فایل جیسون لیست نمادها را بروز کنیم.

توجه: حتما باید نام نماد مقایسه شود برای برخی نمادها مانند دی - بانک دی که اسم کوتاهی دارند بجای نماد میتوان از اسم سهم استفاده کرد البته لزوما اسم سهم ها یکسان نیستند و ممکن است در تایپ دقت کافی صورت نگرفته باشد مانند سهم شمواد که در اسم قدیمی فاصله بین لغات درست درج نشده است. (بانک دی نماد قدیمی ندارد فقط به عنوان مثال آورده شده است) 
</p>

**Comment by Glyphack** [comment]
جالب بود این مورد بنظرم چون چیزی هست که خیلی دقیق نیست باید یه کدی بنویسیم که به لیست نمادهایی که توی پکیج هست(یه فایل جیسون هست) برای هر نماد نمادهای قدیمی اون رو هم داشته باشه طوری که بدونه مثلا یه نماد با چه آیدی هایی فعال بوده. و اینطوری میشه دیتا رو گرفت
خوبی اینکه کد اتوماتیک نباشه اینه که میشه یه بار ریویو کرد
مثال این کار خود همین فایل هست که الان یه کدی هست که این فایل رو آپدیت میکنه و میشه ریویو  کرد تغییرات رو و مطمئن شد آدرس‌ها صحیح هستند.

**Comment by alised** [comment]
دارم روی ترکیب دیتای قدیمی کار می کنم اگر ممکنه بفرمایید نحوه بروزرسانی فایل جیسون به چه صورت است و اینکه این الگو برای ذخیره اندیس نمادهای قدیمی مناسبه؟
`{
  "آبادا": {
    "index": "37661500521100963",
    "code": "IRO1NBAB0001",
    "name": "تولید نیروی برق آبادان",
    "old": [
      "18621338450655320"
    ]
  },
  "آپ": {
    "index": "55254206302462116",
    "code": "IRO1APPE0001",
    "name": "آسان پرداخت پرشین",
    "old": []
  },
}`

**Comment by Glyphack** [comment]
سلام فایل جیسون به این شکل بروزرسانی میشه
توی پوشه scripts
یه فایل به اسم 
update_symbols_json
هست که توی اون کد بروزرسانی فایل جیسون وجود داره
نام و اطلاعات نمادهارو هم از دوتا صفحه میگیره برنامه
این دوتا تابع رو نگاه کنید
get_market_symbols_from_market_watch_page
get_market_symbols_from_symbols_list_page
البته توی چند روز آینده یه تغییری توی این قسمت قراره بدم ولی کلیت ماجرا همینه

**Comment by Glyphack** [comment]
آره این نحوه ذخیره کردن خیلی مناسبه اگر بشه این کارهایی که میکنید هم به شکل یه اسکریپت باشه مثل همینی که الان فایل جیسون رو آپدیت میکنه خیلی عالی میشه
