### ISSUE TITLE
دریافت اطلاعات نماد حذف شده به جای نماد جدید

### ISSUE THREAD

**Issue by soroush-mim** [Glyphack/pytse-client#123]
در دریافت اطلاعات حقیقی حقوقی برخی از سهم ها (برای مثال الان برای من مشکل در مورد سهم تمحرکه اتفاق افتاده)
به جای دریافت اطلاعات حقیقی حقوقی نماد جدید، اطلاعات حقیقی حقوقی نماد حذف شده دریافت میشود

tse.Ticker(symbol).client_types
در این کد برای مثال اگر به جای 
symbol
تمحرکه قرار بدیم اطلاعات حقیقی حقوقی نماد حذف شده را دانلود میکنه. این مشکل در مورد نسخه پایینتر پایتون (۳٫۸) برای نمادهای بیشتری در مقایسه با نسخه ۳٫۹ پیش میاید

**اطلاعات سیستم:**
 - سیستم عامل: مثل ویندوز و اوبونتو هر دو امتحان شده
 - ورژن پایتون ۳٫۹

**Comment by soroush-mim** [comment]
بنظر میاد ایندکس این سهم توی فایل
symbols_data.json
مربوط به نماد حذف شدس

**Comment by Glyphack** [comment]
آره این نمادا از روی دوتا آدرس گرفته میشن اولی اینجاست
http://www.tsetmc.com/Loader.aspx?ParTree=111C1417
و دومی دیدبان بازاره بنظر میاد یه سری نماد توی این لیست آپدیت نیستن
کد رو تغییر میدم که دیدبان بازار منبع اصلی باشه فعلا.

**Comment by soroush-mim** [comment]
بنظر میاد دلیل این مشکل مربوط به تابع 
replace_arabic
توی فایل 
persian.py
باشه
توی نماد تمحرکه چون حرف ک رو داریم این تابع باعث میشه که توی تابع 
get_symbol_id
توی شرط اخر که اسم نماد رو چک میکنه شرط برقرار نباشه و در نتیجه تابع مقدار
None
برمیگردونه
