### ISSUE TITLE
پیشنهاد برای بهتر شدن

### ISSUE THREAD

**Issue by KianMaghsoodi** [Glyphack/pytse-client#13]
I wanted to type this out in Farsi, but since Github's styling is not so Farsi-friendly, I will try out my best in English:

Before I start, I have to say that you are doing god's work here :) Thank you so much for all of your efforts. There is no one time official solution for getting the TSE's data, and their TseClient software is as shitty as their website. Here goes all of my recommendations for you:

So the First thing I noticed is that, you library returns back some kind of TimeOut Error while trying to scrape data from TSETMC, which was somehow solved by running the cell `tickers = tse.download(symbols="all", write_to_csv=True)` multiple times (I use Jupyter Notbook as my development environment). After 4 tries and getting TimeOut Error in the first two,  I had 583 csv file in "tickers_data" folder, which I think is still incomplete, after the third try the error went away and the number of csv file didn't  increase either.

The second thing I noticed is that your library won't scrape the ETFs data, which is also a flaw.

These are the one that I have came across so far, will notify you if I find anything new.

**Comment by Glyphack** [comment]
Thanks for giving your feedback :)

> you library returns back some kind of TimeOut Error while trying to scrape data from TSETMC

It would be better if you put the error you got, but in general this happens when tsetmc does not return appropriate response after (10 retries!) And I decided to not retry anymore when this state is reached. if we can find a pattern about how should be retry we can use other solutions. Also when you download and package fails to download all symbols it should print a warning, didn't you get it?

> The second thing I noticed is that your library won't scrape the ETFs data, which is also a flaw.

What is ETFs data?

**Comment by TheC0d3Mast3r** [comment]
سلام به شما، من ندیدم جوابتونو و واقعا معذرت می خوام.
ای تی اف مثلا آگاس یا سرو یه سری صندوقن و داده هاشون باشه می شه یه سری حرکات در راستای آپتیمایز کردن پورتفولیو زد مثلا.

من چندتا پیشنهاد داشتم که بر اساس مشکلاتی هست که توی این مدت بهشون بر خوردم

دیتای ما در بهترین حالت 4000 خطه که اصلاکفاف یه مدل عمیق یا هر چیز اینظوری رو نمی ده. اگر مثلا می شده داده برای ساعت یا دقیه باشه حجم داده خیلی بهتر می شد.

در کنار اون داده بورس ایران به خاطر اینکه سهما رو ممکنه یه روز به خاطر افشا یا مجمع ببندن هیچ فرکانس مشخصی نداره، اگر می شد مثلا یه گرینه می ذاشتین که خودش بر اساس چندتا متد آمار داده رو کامل می کرد عالی می شد

**Comment by sfmqrb** [comment]
فکر می‌کنم بهتره تمرکز پکیج روی گرفتن دیتا باشه و نه خیلی بر روی اسموث کردن یا تمیز کردن اون.
هر کسی بر حسب نیازش می تونه این کار رو بکنه
