### ISSUE TITLE
کامل نبودن لیست نمادها

### ISSUE THREAD

**Issue by alised** [Glyphack/pytse-client#131]
باید در بروزرسانی فایل جیسون توجه کنیم که دو منبع مورد استفاده نمادهای متوقف را شامل نمی شوند.
یعنی اگر نمادی برای چند روز هم بسته باشد داخل این لیست ها نمی آید

**Comment by mostafa2msh** [comment]
با سلام من تمام نمادهای اختیار معامله که فعال هستند را بررسی کردم از بین همه نماد ها نمادهای زیر در دیتابیس وجود نداره و با این دستور شناسایی نمیشن:
 tse.Ticker("ضاريا1200")

ضاريا1200
ضاريا1201
ضاريا1202
ضاريا1203
ضاريا1204
ضاريا1205
ضاريا1206
ضاريان1200
ضاريان1201
ضاريان1202
ضاريان1203
ضاريان1204
ضاريان1205
ضاريان1206
طاريا1200
طاريا1201
طاريا1202
طاريا1203
طاريا1204
طاريا1205
طاريا1206
طاريان1200
طاريان1201
طاريان1202
طاريان1203
طاريان1204
طاريان1205
طاريان1206
ضشگويا1200
ضشگويا1201
ضشگويا1202
ضشگويا1203
ضشگويا1204
ضشگويا1205
ضشگويا1206
طشگويا1200
طشگويا1201
طشگويا1202
طشگويا1203
طشگويا1204
طشگويا1205
طشگويا1206
ضكگهر1200
ضكگهر1201
ضكگهر1202
ضكگهر1203
ضكگهر1204
ضكگهر1205
ضكگهر1206
طكگهر1200
طكگهر1201
طكگهر1202
طكگهر1203
طكگهر1204
طكگهر1205
طكگهر1206
ضملي1157
ضملي1158
ضملي1159
ضملي1160
ضملي1161
ضملي1162
ضملي1163
ضملي1164
طملي1157
طملي1158
طملي1159
طملي1160
طملي1161
طملي1162
طملي1163
طملي1164
ضپيك1028
ضپيك1029
ضپيك1030
ضپيك1031
ضپيك1032
ضپيك1033
ضپيك1034
ضپيك1035
ضپيك2018
ضپيك2019
ضپيك2020
ضپيك2021
ضپيك2022
ضپيك2023
ضپيك2024
ضپيك2025
طپيك1028
طپيك1029
طپيك1030
طپيك1031
طپيك1032
طپيك1033
طپيك1034
طپيك1035
طپيك2018
طپيك2019
طپيك2020
طپيك2021
طپيك2022
طپيك2023
طپيك2024
طپيك2025

**Comment by alised** [comment]
در این خط از برنامه نمادهایی که به عدد ختم میشوند حذف می شوند

if symbol name ends with number it's some kind of symbol
like 'حق تقدم' and we don't want it

https://github.com/Glyphack/pytse-client/blob/f45d278d1888470725e98b56af9b678d887045d8/pytse_client/scraper/symbol_scraper.py#L88

**Comment by Glyphack** [comment]
@alised میدونی نمادهای حذف شده رو از کجا میشه گرفت؟

**Comment by alised** [comment]
منظورتان نمادهایی است که موقت بسته شده اند یا نمادهای قدیمی که دیگه فعال نیستند؟
منبع مناسبی برای نمادهای قدیمی حذف شده بجز همان صفحه جستجوی نماد سایت tsetmc سراغ ندارم.
سایت سازمان وب سرویس تجاری دارد در آن لیست همه نمادها حتی حذف شده میاد تا سال ۹۳ رایگان بود ولی بعد از آن هزینه ماهانه میگیرد.

**Comment by alised** [comment]
@Glyphack 
داشتم کدهای tse client را نگاه می کردم که چطوری دیتای تمامی سهام حتی حذف شده و قدیمی ها را با هم ترکیب کرده ام که متوجه شدم در آنجا نمادهای قدیمی هم می آورد از این لینک استفاده کنید:
http://service.tsetmc.com/tsev2/data/TseClient2.aspx?t=Instrument&a=0

**Comment by Glyphack** [comment]
@alised آره الان دقیقا از همون سرچ استفاده می‌کنیم برای پیدا کردن نمادهای قدیمی
فعلا اوکی عمل کرده برنامه حتی اگر یه نمادی برای یه مدت کوتاه هم متوقف بشه اون لیست آپدیت میشه و نماد در حالت متوقف قراره میگیره.

**Comment by alised** [comment]
@Glyphack لینک دادم بالا نگاه کنید

**Comment by Glyphack** [comment]
این لینک بنظر خوب میاد که اضافه کنیم. داخلش تمام نمادهای فعال و غیرفعال رو داره؟

**Comment by alised** [comment]
@Glyphack  موردی بررسی کردم ولی اینکه آیا همه نمادها بدون مشکل هستند یا خیر نگاه نکردم.
به هر حال لینکی است که نرم افزار سازمان ازش استفاده می کند.
مثلا نماد نوین (بیمه نوین) را سرچ کرده بودم.
نکته دیگه اینکه فقط سهام و شاخص را شامل میشود و دیتای مثلا اختیارها را ندارد.

**Comment by AlirezaHanifi** [comment]
اگه اشتباه نکنم لیست نمادها از این قطعه کد پایین میادش. 
https://github.com/Glyphack/pytse-client/blob/f45d278d1888470725e98b56af9b678d887045d8/pytse_client/tse_settings.py#L38-L40
حالا مشکلم این‌ه که بعضی از نمادهایی که به تازگی نمادشون روی تابلو اومده مثل: آكام و استيل با اسم‌شون نمی‌تونم داده‌هاشون رو بگیرم (در حالی‌که این دو تا نماد توی لینک بالا هستن). البته در نهایت میشه با استفاده از ایندکس‌شون رو داده گرفت ولی خب در نهایت تاریخ جلالی و اینا نمی‌ده و حالا اون رو هم میشه حل کرد ولی خب تمام ایندکس‌ها رو ندارم و باید کار دستی بکنم. آیا من جایی رو اشتباه کردم یا نه و مشکل از پکیج‌ه؟
![Screenshot 2023-08-05 194010](https://github.com/Glyphack/pytse-client/assets/61773811/f2ea27a1-21d8-4ff2-a9b9-5657d908af7a)

**Comment by Glyphack** [comment]
سلام @AlirezaHanifi نمادها ازون لینک گرفته میشه اما توی فایل `symbols.json` ذخیره میشه و دستی آپدیت میشه. باید یه بار دیگه اسکریپت آپدیت کردن این رو اجرا کنید. فایلش توی پویشه scripts هست.

**Comment by Glyphack** [comment]
![image](https://github.com/Glyphack/pytse-client/assets/20788334/c6c032f8-5236-49dc-a350-8ae4c51ea237)

بنظرم فعلا بهترین راه اینه که برای نمادهایی که اختیار هستن یا قدیمین ازین روش استفاده بشه. چون لاجیک اوردن اینا توی کد خیلی پیچیده میشه و دیتای غلط ممکنه زیاد بشه.
