### ISSUE TITLE
 زمانی که روی هاست یک سهام فراخوانی می کنم این خطا رو میده

### ISSUE THREAD

**Issue by alised** [Glyphack/pytse-client#149]
سلام خسته نباشید ممنون میشم این مشکل رو هم حل کنید. زمانی که روی هاست یک سهام فراخوانی می کنم این خطا رو میده

Extra data: line 10254 column 2 (char 217578)
Traceback (most recent call last):
  File "/home/optionto/virtualenv/bot/3.9/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/optionto/bot/plugins/send_file.py", line 119, in main
    tse.download(symbols=text)
  File "/home/optionto/bot/pytse_client/download.py", line 42, in download
    ticker_index = _handle_ticker_index(symbol)
  File "/home/optionto/bot/pytse_client/download.py", line 264, in _handle_ticker_index
    ticker_index = symbols_data.get_ticker_index(symbol)
  File "/home/optionto/bot/pytse_client/symbols_data.py", line 21, in get_ticker_index
    return symbols_information().get(ticker_symbol, {}).get("index")
  File "/home/optionto/bot/pytse_client/symbols_data.py", line 16, in symbols_information
    ticker_name_to_index_mapping = json.load(symbols_name)
  File "/opt/alt/python39/lib64/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/opt/alt/python39/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/alt/python39/lib64/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 10254 column 2 (char 217578)

_Originally posted by @mostafa2msh in https://github.com/Glyphack/pytse-client/issues/136#issuecomment-991745459_

**Comment by alised** [comment]
سلام
اگر روی لوکال مشکلی ندارید ولی روی هاست خطا دریافت می کنید. اول عدم دسترسی به وب سرویس بورس از روی هاست را بررسی کنید.
بعد نسخه پایتون و پکیج های ضروری نصب شده را بررسی کنید.

**Comment by mostafa2msh** [comment]
با سلام و تشکر. هاست دسترسی به وب سرویس بورس داره. پکیج ها هم نصب هستند . دلیلش هم اینه که این خطا همیشه ظاهر نمیشه و برخی اوقات به درستی کار میکنه.

**Comment by alised** [comment]
لطف می کنید اگر شرایطی که با مشکل مواجه می شوید را کامل توضیح دهید. کدتان هم قرار بدید بهتر است. احتمال زیاد برنامه در این قسمت دچار خطا میشود
get_shareholders_history
تعداد درخواست های زیادی بصورت همزمان ارسال می کنید؟ گاهی وب سرویس بورس اصلا جواب نمیده یا به علت درخواست بالا برای مدتی آی پی شما را بلاک می کند بنابراین تعداد درخواست های همزمان خود را مدیریت کنید.
خطا را کچ کنید تا در صورت مواجه شدن با خطا بتونید با چند ثانیه تاخیر مجدد درخواست را ارسال کنید.
میتوانید یک لیست پراکسی هم داشته باشید تا در صورت بن شدن آی پی سرور از آنها استفاده کنید.

برخی از آیپی های وب سرویس دیتاشون مشکل داره از اونها استفاده نکنید توی فایل تنظیمات برید و بجای دامین آیپی سالم را قرار دهید.
به این مطلب مراجعه کنید
https://github.com/Glyphack/pytse-client/issues/119#issuecomment-920375748

**Comment by mostafa2msh** [comment]
با سلام و تشکر از راهنماییتون. دقیقا متوجه نشدم مشکل چیه اما چیزی که متوجه شدم زمانی که نمادی رو که در فایل symbols_name.json وجود نداره رو فراخوانی میکنیم "ممکنه" این اتفاق بیوفته و دیگه ربات کار نمیکنه. برای حل این مشکل تنها راهی که به ذهنم رسید حذف فایل جیسون و اپلود فایل اصلیش از پکیج بود که جواب داد.
