### ISSUE TITLE
مشکل کار نکردن پکیج در colab

### ISSUE THREAD

**Issue by vdfdfhgbstdh** [Glyphack/pytse-client#15]
**توضیح مشکل پیش آمده**
سلام 
زمانی که طبق راهنمایی ارائه شده میخوام که داده ها دانلود بشن در نهایت با ارور 
"time out"
فرایند متوقف میشه. این ارور تو محیط 
colab
داده میشه. اما وقتی که لینک های سایت رو تو فایل ستینگ بررسی کردم متوجه شدم احتمالا لینک ها تغییر کردن دوباره
متن ارور:

`timeout: timed out

During handling of the above exception, another exception occurred:

ConnectTimeoutError                       Traceback (most recent call last)
ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f8b93e752e8>, 'Connection to tsetmc.com timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
MaxRetryError: HTTPConnectionPool(host='tsetmc.com', port=80): Max retries exceeded with url: /tsev2/data/Export-txt.aspx?t=i&a=1&b=0&i=778253364357513 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8b93e752e8>, 'Connection to tsetmc.com timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

ConnectTimeout                            Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    502                 # TODO: Remove this in 3.0.0: see #2811
    503                 if not isinstance(e.reason, NewConnectionError):
--> 504                     raise ConnectTimeout(e, request=request)
    505 
    506             if isinstance(e.reason, ResponseError):

ConnectTimeout: HTTPConnectionPool(host='tsetmc.com', port=80): Max retries exceeded with url: /tsev2/data/Export-txt.aspx?t=i&a=1&b=0&i=778253364357513 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8b93e752e8>, 'Connection to tsetmc.com timed out. (connect timeout=10)'))`

**Comment by Glyphack** [comment]
بنظر میاد سایت بورس جواب نداده، موقع دانلود اطلاعات همه سهم‌ها پیش اومده؟

**Comment by vdfdfhgbstdh** [comment]
> بنظر میاد سایت بورس جواب نداده، موقع دانلود اطلاعات همه سهم‌ها پیش اومده؟

تو قسمت راهنما یه کد برای دانلود همه سهم ها گذاشتین یکی هم **وبملت** که در دو حالت هم با همین ارور مواجه میشه. بقیه نماد ها رو بررسی نکردم

**Comment by Glyphack** [comment]
مشکل از سایت بورس هست احتمالا ولی من یه سری کار ها مثل ریترای کردن انجام دادم برای اینکه ارور پیش نیاد باید راه‌های دیگه‌ای هم پیدا کرد.

**Comment by vdfdfhgbstdh** [comment]
> مشکل از سایت بورس هست احتمالا ولی من یه سری کار ها مثل ریترای کردن انجام دادم برای اینکه ارور پیش نیاد باید راه‌های دیگه‌ای هم پیدا کرد.

آیا براتون مقدوره که دیتاست تاریخچه بورس رو جایی آپلود کنین؟
البته نمیدونم حجمش چقدره اما اگه امکانش بود جایی آپلود بشه خیلی خوب میشد.

**Comment by vdfdfhgbstdh** [comment]
> مشکل از سایت بورس هست احتمالا ولی من یه سری کار ها مثل ریترای کردن انجام دادم برای اینکه ارور پیش نیاد باید راه‌های دیگه‌ای هم پیدا کرد.

وقتی که به صورت دستی لینک رو استفاده میکنم فایل دانلود میشه. به این وصرت
`TSE_TICKER_EXPORT_DATA_ADDRESS = (
    "http://tsetmc.com/tsev2/data/Export-txt.aspx?t=i&a=1&b=0&i={}"
)`
و آی دی وبملت :778253364357513

`http://tsetmc.com/tsev2/data/Export-txt.aspx?t=i&a=1&b=0&i=778253364357513`
فایل 
csv
دانلود میشه. ایا بنظرتون مشکل از پکیجه؟؟

**Comment by vdfdfhgbstdh** [comment]
> مشکل از سایت بورس هست احتمالا ولی من یه سری کار ها مثل ریترای کردن انجام دادم برای اینکه ارور پیش نیاد باید راه‌های دیگه‌ای هم پیدا کرد.

الان لوکال امتحان کردم و پکیج مشکلی نداشت.
اما رو محیط 
colab
نمیشه دانلود کرد

**Comment by Glyphack** [comment]
توی اون محیط میشه به سایت بورس وصل شد اصلا؟
