### ISSUE TITLE
problem in colab

### ISSUE THREAD

**Issue by drAliRahnema** [Glyphack/pytse-client#150]
in colab i can not run your api. 
it needs proxy
can you help me

**Comment by Glyphack** [comment]
We don't have any Iran IP proxies to be used. If there's any it can be set on http requests and problem should be solved.
If not one other way is to manually getting the data and uploading to GDrive and using it from Colab.

**Comment by Glyphack** [comment]
در حال حاضر نمیشه درباره این ایشو کاری کرد میبندمش اگر دوباره خواستید بازش کنید لطفا توی https://github.com/Glyphack/pytse-client/discussions
مطرحش کنید.
