### ISSUE TITLE
افزودن جزئیات به get_ticker_real_time_info_response

### ISSUE THREAD

**Issue by Jarrahi-MM** [Glyphack/pytse-client#153]
<p dir="rtl">

**مشکلی که دارید چی هست؟**
تابع get_ticker_real_time_info_response کامل نیست و برخی اطلاعات را ندارد.

**راه حل**
در response ای که در همین تابع داریم، میتونیم این اطلاعات را به دست بیاوریم.

**نکات تکمیلی**
<img width="476" alt="Screen Shot 1400-11-23 at 13 49 14" src="https://user-images.githubusercontent.com/44052346/153708469-839c1755-48d9-48e8-b6c2-62f436540ccf.png">

</p>

**Comment by alised** [comment]
مواردی که به فارسی توضیح داده اید که همه در تابع مذکور وجود دارد. اگر مقدار خاصی مد نظر شماست بفرمایید که اضافه شود.

`‍‍‍‍‍‍‍```
import pytse_client as tse
ticker = tse.Ticker(symbol="نوری", adjust=True)
ticker.get_ticker_real_time_info_response()

Out[4]: RealtimeTickerInfo(state='مجاز', last_price=87990, adj_close=89000, yesterday_price=90480, open_price=90800, high_price=91100, low_price=87900, count=3350, volume=1652792, value=147098122190, last_date=datetime.datetime(2022, 2, 12, 12, 30), best_demand_vol='125', best_demand_price='87820', best_supply_vol='1700', best_supply_price='87990', sell_orders=[order(count='1', volume='1700', price='87990'), order(count='1', volume='446', price='88050'), order(count='1', volume='50', price='88200'), order(count='1', volume='3440', price='88280'), order(count='2', volume='909', price='88290')], buy_orders=[order(count='1', volume='125', price='87820'), order(count='6', volume='1177', price='87800'), order(count='1', volume='100', price='87760'), order(count='1', volume='60', price='87710'), order(count='2', volume='1000', price='87700')], individual_trade_summary=TradeSummary(buy_vol=1378530.0, buy_count=1354.0, sell_vol=1637675.0, sell_count=758.0), corporate_trade_summary=TradeSummary(buy_vol=274262.0, buy_count=3.0, sell_vol=15117.0, sell_count=2.0), nav=None, nav_date=None)
````

**Comment by Jarrahi-MM** [comment]
> درسته. من نسخه‌ی 0.10 را استفاده می‌کردم.
