### ISSUE TITLE
امکان گرفتن موقعیت باز و اندازه قرارداد از جزییات  هر سهام

### ISSUE THREAD

**Issue by tahericode** [Glyphack/pytse-client#159]
<p dir="rtl">

**مشکلی که دارید چی هست؟**
قابلیت دریافت اطلاعات فلان امکان پذیر نیست

**راه حل**
میتونیم از این صفحه این اطلاعات رو دریافت کنیم و به برنامه اضافه کنیم

**نکات تکمیلی**
اگر عکس و یا نکته‌ای هست که برای پیاده‌سازی مهم هست اینجا بگید.

</p>

**Comment by tahericode** [comment]
سلام و خداقوت..امکان اینکه بتونیم موقعیت باز و اندازه قرارداد را بگیریم داخل این نسخه هست؟

**Comment by Glyphack** [comment]
سلام،
راستش من با این دوتا اصطلاحی که گفتید آشنا نیستم میشه با توضیح بیشتر و مثال اینکه شما این‌هارو چطور محاسبه میکنید(اگر لینکی به جایی هم داشته باشید خوبه) بنویسید؟
برای اینکه بقیه افراد هم این رو ببینن و کمک کنند میتونید از خود گیتهاب برای این سوال استفاده کنید اینجا راهنمای اینکه چطور گزارش رو بنویسید نوشتم:
https://github.com/Glyphack/pytse-client/blob/master/CONTRIBUTING.md#%D9%BE%DB%8C%D8%B4%D9%86%D9%87%D8%A7%D8%AF-%D8%A8%D9%87%D8%A8%D9%88%D8%AF <https://github.com/Glyphack/pytse-client/blob/master/CONTRIBUTING.md#%D9%BE%DB%8C%D8%B4%D9%86%D9%87%D8%A7%D8%AF-%D8%A8%D9%87%D8%A8%D9%88%D8%AF>

**Comment by sfmqrb** [comment]
اندازه قرارداد برای بازار آتی تعریف شده است و واژه موقعیت باز هم مربوط به بازار آتی هست و به سهام ربطی نداره

**Comment by Glyphack** [comment]
من این رو میبندم چون نمیدونیم چه کاری باید انجام بشه. دوباره میتونید باز کنید اگر اطلاعات کامل تر شد.
