### ISSUE TITLE
دسترسی به اطلاعات فیلتر نویسی

### ISSUE THREAD

**Issue by Glyphack** [Glyphack/pytse-client#160]
<p dir="rtl">

**مشکلی که دارید چی هست؟**
به اطلاعاتی از نماد که در صفحه فیلتر نویسی موجود است دسترسی داشته باشم

**راه حل**
میتوانیم از api سایت که همه‌ی اطلاعات لازم برای فیلتر نویسی را در صفحه دیدبان موجود است استفاده کنیم

**نکات تکمیلی**
- برای برخی ازین اطلاعات تاریخچه مهم است و دیدبان تمام تاریخچه را نمیدهد. این گونه ویژگی‌ها بهتر است که از طریقی اضافه شوند که شامل تاریخچه‌ی کامل تر باشند.

این تیکت در طول زمان آپدیت خواهد شد
</p>

**Comment by sfmqrb** [comment]
هرچند در #163 تنها دیتایی که نداشتیم به پگیج اضافه شد ولی همچنان به نظرم باید تمامی دیتا که برای فیلترنویسی در اختیارمان قرار میگیرد را بتوانیم در قالب یک دیتافریم به کاربر بدهیم. حتی اگر روش های دیگری برای گرفتن دیتا داریم.
علت این اصرار سرعت و جامعیت ماژول برای فیلترنویسی است.
البته به شکلی کد زده شده است که با پیاده سازی صرفا بخش های دیگر دیتا که ریکوئست های متفاوت دارند بتوان به راحتی داخل دیتافریم دیتای تازه استخراج شده را چید.
سر فرصت این ایشو را ادامه خواهم داد صرفا اینجا گفتم تا ایشو بسته نشود.
