### ISSUE TITLE
دیتای عمق بازار 

### ISSUE THREAD

**Issue by sfmqrb** [Glyphack/pytse-client#161]
<p dir="rtl">

**مشکلی که دارید چی هست؟**
دسترسی به دیتای عمق بازار 

**راه حل**
هنوز بررسی نکرده ام که آیا این دیتا از طریق tsetmc در دسترس قرار دارد یا خیر ولی از طریق OMS ها قابل دسترسی است مثل تدبیر

**نکات تکمیلی**
تفاوت این دیتا با دیتای پنج مظنه برتر کامل تر بودن آن است. 

![Screenshot from 2022-04-18 12-00-51](https://user-images.githubusercontent.com/45316558/163773093-88727ec9-1b0f-4949-b686-dcd968033930.png)

در تصویر بالا دیتای عمق بازار را در oms تدبیر مشاهده می‌کنید.

</p>

**Comment by sfmqrb** [comment]
برای دیتای تاریخی پنج مظنه اول به راحتی میشه از این http://cdn.tsetmc.com/api/BestLimits/19040514831923530/20220410
استفاده کرد.

**Comment by sfmqrb** [comment]
با توجه به اینکه خود این پنج مظنه اول به اندازه کافی خودشون حجیم هست به نظرم برای دیتای تاریخی مناسبه روی همین کار کنیم. 
کد پیچیده ای نیست. دولوپش میکنم در روزهای پیش رو. @Glyphack

**Comment by Glyphack** [comment]
مرسی بابت این و همه‌ی کارای دیگه‌ای که کردی. کمکی لازم بود بهم بگو @sfmqrb

**Comment by Glyphack** [comment]
اینو تا بخشی توی order book داریم و تصمیم گرفتیم که فعلا جلو نبریم.
