### ISSUE TITLE
Ticker::_history outdated data

### ISSUE THREAD

**Issue by sfmqrb** [Glyphack/pytse-client#166]
**کلیت مشکل**
ایراد در Ticker::_history برخی مواقع در صورت وجود فایل تاریخچه در `base_path` ممکن است دیتافریم آپدیت نشده استفاده شود.

گام های زیر را به ترتیب انجام دهید.

```python
from pytse_client import download
download("وغدیر", write_to_csv=True)
```
حال چند سطر آخر فایل csv را پاک کنید.(انگار فایل را چند روز پیش دانلود کرده اید)

```python
from pytse_client import Ticker
t = Ticker("وغدیر")
print(t.history)
```

خروجی ناقص خواهد بود و چند روز پاک شده را در تاریخچه سهم نمی‌آورد در صورتی که انتظار این است که این اتفاق بیفتد مستقل از وجود فایل یا عدم وجود آن.

علت این مشکل این است که فرض خواندن از فایل در کلاس Ticker و تابع from_file فرض آسانگیرانه ای است و تاریخ آخرین روز معاملاتی با امروز را چک نمی کند که فایل را ابتدا آپدیت کرده و سپس تاریحچه نماد را نشان دهد.

![Screenshot from 2022-05-02 16-29-20](https://user-images.githubusercontent.com/45316558/166230223-17cc42d5-17f9-4c2f-a9c9-3d7ff79da411.png)

**Comment by Glyphack** [comment]
وقتی کاربر میخواهد سابقه‌ی سهام را با Ticker بگیرد چک کنیم اگر آخرین تاریخ باز بودن بازار آن تاریخ نیست از طریق API روزهای دریافت نشده را بگیریم و مرج کنیم.
