### ISSUE TITLE
 امکان اضافه کردن قیمت لحظه ای تمامی نماد های بازار در یک رکوست 

### ISSUE THREAD

**Issue by aemamj** [Glyphack/pytse-client#170]
<p dir="rtl">

با سلام و عرض احترام از آنجا که شما در پکیجتون امکان قیمت لحظه ای را قرار دهید در صورت امکان دریافت قیمت تمامی نماد های بازار با یک رکوست  رو می توانید بگذارید؟
در قسمتی که در پکیج هست برای گرفتن قیمت لحظه ای باید نام تک تک  نماده ها رو هر بار رکوست کرد و این خیلی زمان بر هست .  پیشنهاد من این که میتونید یک قسمت جدا برای همه نمادها در یک رکوست داشته باشید .  البته این رو اضافه کنم چیزی که هست میتونه برای لحظه ای پیشرفته نماده با جزیات بیشتر مورد استفاده قرار بگیره 
علاو بر این که میتوان اطلاعات کل نماد های بوس در یک رکوست ، اطلاعات کل شاخص بورس در هر لحظه را هم داشت  
راه حل
می توانید از این صفحه[ دیدبان بازار پیشرفته](http://www.tsetmc.com/Loader.aspx?ParTree=15131F#) اطلاعات را دریافت کنید و به برنامه اضافه کنید

با تشکر
</p>

**Comment by Glyphack** [comment]
@aemamj سلام این قابلیت هنوز اضافه نشده پیشنهاد میکنم ایشو رو باز نگه داریم تا یادمون نره.

**Comment by sfmqrb** [comment]
این قابلیت الان با تابع get_stats اضافه شد
@Glyphack ایشو رو می تونیم ببندیم
