### ISSUE TITLE
آدرس سرورهای مرتبط با pytse_client

### ISSUE THREAD

**Issue by ADanayi** [Glyphack/pytse-client#172]
<p dir="rtl">
سلام و عرض ادب

مدتی هستش که روی سروری که از pytse_client استفاده می‌کنم دیگه نمی‌تونم داده‌ای دریافت کنم، اما روی سیستم شخصی بدون مشکل کار می‌کنه. امکانش هست لیست سرورهایی pytse_client باهاشون کار می‌کنه رو بنویسید تا بتونم ping بگیرم ببینم مشکل از کجاست؟

ممنونم
</p>

**Comment by Glyphack** [comment]
سلام بله ليست آدرس‌ها توی فایل پروژه هست توی پوشه pytse_client فایل tse_setting

**Comment by ADanayi** [comment]
سلام مجدد
تشکر فراوان...

**Comment by Glyphack** [comment]
بنظر مشکل حل شده من این ایشو رو میبندم
