### ISSUE TITLE
مشکل دریافت سابقه سهامدران عمده

### ISSUE THREAD

**Issue by albuser2022** [Glyphack/pytse-client#173]
**توضیح مشکل پیش آمده**

ticker = tse.Ticker("وبملت")
ticker.get_shareholders_history(
    from_when=datetime.timedelta(days=90),  # تعداد روز‌های گذشته که مقدار پیشفرض ۹۰ روز است
    to_when=datetime.datetime.now(),  # تا چه تاریخی اطلاعات گرفته شود که پیشفرض امروز است
    only_trade_days=True,  # فقط روز‌های معاملاتی که پیشفرض بله است
)
این تیکه کد رو  وقتی اجرا میکنم به خطای asyncio.run() cannot be called from a running event loop بر میخورم 
**چطور اتفاق افتاد؟**
کاری که میکردید که باعث شد این اتفاق بیوفته:
1. اطلاعات همه سهام ها را دانلود کردم
2. سعی داشتم اطلاعات معاملات سهم فلان رو بگیرم با دستورات زیر
3. ارور زیر را گرفتم(متن کامل ارور)

**انتظار دارید چه اتفاقی بیوفته**
انتظار دارید که با اعمال بالا چه اتفاقی در برنامه بیوفته

**اسکرین شات**
اگر چیزی هست که تصویر لازم داره اون رو اینجا قرار بدید

**اطلاعات سیستم:**
 - سیستم عامل: مثل ویندوز ۱۰
 - ورژن پایتون
 - محیطی که توش کار میکردید( سی ام دی، پاورشل یا بش)
Python 3.9.7  و jupyter
**اطلاعات اضافی**
اگر چیزی هست که لازمه گفته بشه و توی اطلاعات بالا نیست اینجا بنویسید

**Comment by Glyphack** [comment]
توی جوپیتر چون دستورات async توی کد اصلی ساپورت میشه این مشکل پیش میاد. 
ازین مثال استفاده کنید 
https://github.com/Glyphack/pytse-client/blob/master/pytse_client/examples/download_shareholders_history_aync.py
خط آخر رو ولی به
get_shareholders_history()
تغییر بدید.

این ایشو رو باز میکنم که توی داکیومنت توضیح رو اضافه کنم.

**Comment by nimahemmati** [comment]
سلام.
فانکشن get_shareholders_history() دیتا رو تا حدود یک ماه قبل برمیگردونه. یعنی اخرین دیتایی که از این تابع میشه گرفت برای 07/06 هست. ممکن هست این مورد رو هم بررسی کنین؟

**Comment by nimahemmati** [comment]
سلام .
فانکشن get_shareholders_history() دیتا رو تا یک ماه قبل برمیگردونه. یعنی اخرین دیتایی که با این تابع برمیگرده حدودا برای 07/06 هست. ممکن هست این مورد رو هم برررسی کنین؟

**Comment by Glyphack** [comment]
سلام @nimahemmati میتونید تایم گرفتن دیتا رو مشخص کنید اینجا نمونش هست
https://github.com/Glyphack/pytse-client/blob/master/pytse_client/examples/download_shareholders_history.py
