### ISSUE TITLE
به روزرسانی آدرس دریافت اطلاعات

### ISSUE THREAD

**Issue by Baft** [Glyphack/pytse-client#174]
سلام وقت بخیر .
پیشنهاد میکنم آدرس های مرتبط، جهت دریافت اطلاعات عمومی« مثل تاریخچه قیمت و لیست سهام ها به همراه اطلاعاتشان.....» به ادرس های 
به کار رفته در این برنامه [tse client npm](https://www.npmjs.com/package/tse-client#tsecolumnlist) تغییر دهید 
tse client npm همان برگردان شده ی tse-cliect به زبان جاوااسکریپ هست.
 استفاده از آن آدرس ها امکانات بهتری ارایه میدهد . مخصوصا در مورد به روزرسانی تاریخچه.

**Comment by Glyphack** [comment]
سلام منظورتون این هست که فیلد‌هایی که این برنامه برای تاریخچه میده رو اضافه کنیم؟
این کد رو یه بار قبلا چک کردم، خیلی پیچیده نوشته شده و اصلا اطمینانی ندارم که چطوری کار میکنه که بیارم که استفاده کنم. اگر بخوام تغییری روش بدم نمیتونم.

**Comment by sfmqrb** [comment]
منظورتون در مورد بروزرسانی تاریخچه رو بیشتر توضیح بدید لطفا @Baft

**Comment by alised** [comment]
> سلام وقت بخیر . پیشنهاد میکنم آدرس های مرتبط، جهت دریافت اطلاعات عمومی« مثل تاریخچه قیمت و لیست سهام ها به همراه اطلاعاتشان.....» به ادرس های به کار رفته در این برنامه [tse client npm](https://www.npmjs.com/package/tse-client#tsecolumnlist) تغییر دهید tse client npm همان برگردان شده ی tse-cliect به زبان جاوااسکریپ هست. استفاده از آن آدرس ها امکانات بهتری ارایه میدهد . مخصوصا در مورد به روزرسانی تاریخچه.

میتوانید از این ماژول پایتون استفاده کنید:
https://github.com/alised/tse-index

**Comment by Glyphack** [comment]
من این رو میبندم چون پکیج رو بزودی از old.tse به سایت جدید میبریم بنظرم خودش improvement هست.
