### ISSUE TITLE
مشکل در قیمت های نماد «رتکو» 

### ISSUE THREAD

**Issue by Aquarii** [Glyphack/pytse-client#175]
![image](https://user-images.githubusercontent.com/8092720/179180847-59c5f39d-22b0-49b4-b407-e832bd9dc44e.png)
هیچ کدوم از اطلاعات ریل تایم رو نمیده. `get_ticker_real_time_info_response` . فقط برای نماد رتکو. برای بقیه نمادها اوکیه.
نکته: نماد «رتکو» ورشکست شده و در بورس لغو پذیرش شده و به بازار پایه فرابورس فرستاده شده. ولی انگار هنوز کارهاش انجام نشده و همچنان در لیست نمادهای بورس هست.
البته توی  داک سترینگ همون متد خودتون هم گفتید ک حواستون ب none type باشه. ولی باز فرستادم. شاید نیاز ب ریویو داشته باشه.
![image](https://user-images.githubusercontent.com/8092720/179255366-9bc3ccd4-4fed-4f39-b7e1-bf878bd52a0b.png)

**Comment by sfmqrb** [comment]
@Glyphack 
ممکنه symbol_name.json نیاز به آپدیت داشته باشه؟

**Comment by Glyphack** [comment]
آره همین هست دقیقا 
@sfmqrb

**Comment by Glyphack** [comment]
فکر میکنم برای این نمادها باید توی تیکر چک کنیم که اگر نماد قدیمی یا حذف شده هست موقع دسترسی به اطلاعات لحظه‌ای یه خطا بده که پیغام بهتری منتقل بشه. راه دیگه هم میتونه این باشه که کلا توابع کار کردن با نماد حذف شده و فعال فرق بکنه.

راه اول رو ترجیح میدم چون اضافه کردن دستورات جدید داکیومنت کردن و اینا داره اما با راه اول تقریبا همه جا باید توی توابع حواسمون باشه که این نماد فعال هست یا نه تا یه سری از توابع واسش کار نکنن.

**Comment by Glyphack** [comment]
بنظرم کار خیلی آسونی که بشه فعلا انجام داد این هست که یه پیغام هشدار داده بشه از طرف پکیج وقتی این توابع روی یک نماد قدیمی حذف شده صدا میشه.
