### ISSUE TITLE
یک هشدار از سمت پانداز

### ISSUE THREAD

**Issue by DaWatcher79** [Glyphack/pytse-client#178]
درود و سلام. من تازه با این کتابخونه آشنا شدم و شاید اشتباه از خودم باشه اما بهرحال گفتم شاید مطرح کنم بهتر باشه.در خیلی از مواقع این ارور رو شاهد هستم:
C:\Users\acer\anaconda3\lib\site-packages\pytse_client\download.py:127: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_list[symbol].append(

البته نتیجه رو معمولا میده؛صرفا این هشدار رو هم همراهش میده.خواستم اطلاع بدم.در محیط ژوپیتر کار میکنم در ضمن.

 سپاس از زحماتتون راستی,کار بشدت کم نظیریه این کتابخونه شما

**Comment by Glyphack** [comment]
سلام خیلی ممنون که گفتید این نباید خیلی سخت هم باشه درست کردنش بزودی انجام میدم.
