### ISSUE TITLE
اطلاعات امروز

### ISSUE THREAD

**Issue by gpuminingir** [Glyphack/pytse-client#18]
با سلام، آیا امکان هست که دسترسی به اطلاعات امروز (پایان کار حتی( را در برنامه قرار دهید؟

**Comment by Glyphack** [comment]
سلام یکم این اطلاعات دقیقا کدوماست؟

**Comment by gpuminingir** [comment]
اطلاعات موجود در client_types از روز قبل هست، اما اطلاعات لحظه ای و یا حتی پایان وقت معاملات امروز رو نمیاره.

**Comment by Glyphack** [comment]
آره این اطلاعات دیر آپدیت میشه هم این هم اطلاعات معملات از طرف سایت بورس فکر کنم باید از جای دیگه‌ای خونده بشه اطلاعات همون روز.

**Comment by sfmqrb** [comment]
این در get_stats انجام شد
می تونیم ببندیم ایشو رو@Glyphack
