### ISSUE TITLE
مشکل در پارامترهای فیلترینگ

### ISSUE THREAD

**Issue by mr-shirmofakhami** [Glyphack/pytse-client#186]
سلام
در قسمت آخر کد برای دسترسی به پارامترهای فیلترنویسی بعد از اجرا کد به ارور زیر میخورم، اگه میشه راهنمایی کنید
key_stats = get_stats(base_path="", to_csv=False)

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 848: character maps to <undefined>

**Comment by Glyphack** [comment]
این یکم گنگه نیاز داره دقیق تر چک کنم

**Comment by sfmqrb** [comment]
https://bytetool.web.app/en/ascii/code/0x81/
به نظر مشکل 'na' هست.
اگه ارور لاگ کامل بتونید بدید بررسی بهتری میشه کرد.
@mr-shirmofakhami
