### ISSUE TITLE
سوال در مورد این کتابخانه

### ISSUE THREAD

**Issue by ebad84** [Glyphack/pytse-client#19]
سلام
یکی از مشکلاتی که برای من پیش اومده بود این هست که بیایم به صورت لحظه ای اطاعات رو از سایت بگیریم
مثلا اگر الان میزان تقاضا از یک مقداری بالا رفت یک کاری رو انجام بده
الان میتونید راهنمایی کنید که چیکار باید بنکم؟
یک سوال هم داشتم
ببینید توی requests اگر من بخوام بگم بعد از بارگزاری صفحه 5 ثانیه وایستا و بعد اطلاعات رو بده باید چیکار کنم؟
مثلا اگه سایت دیده بان رو دقت کنید متوجه میشین که بعد از بارگزاری حدود 20 ثانیه باید صبر کنیم بعدش برای ما میاد اطاعات رو به نمایش در میاره. اون 20 ثانیه صبر رو چه طوری باید لحاظ کنیم؟
ممنون

**Comment by Glyphack** [comment]
سلام،
این روشیه که سایت بورس کار میکنه خود سایت به یه سری جای دیگه کال میزنه و دیتارو میاره نشون بده. برای بعضی بخش‌ها که به پکیج اضافه شده مثل پی به ای یا قیمت لحظه‌ای لازم نیست سایت کامل لود بشه.
درمورد سوال اول هم برای این سوالا این سرور دیسکورد رو درست کردم چون مستقیم ربطی به پکیج نداره.
https://discord.gg/D3txK6
