### ISSUE TITLE
دریافت اطلاعات برای تاریخ خاص با قیمت صفر 

### ISSUE THREAD

**Issue by mjdehghan** [Glyphack/pytse-client#192]
سلام
وقت بخیر

برای سابقه سهم قچار در سایت tse برای تاریخ 1401/01/08 معاملاتی ثبت نشده

اما برای این سهم در این تاریخ اطلاعات با مقدار حجم معاملات انجام شده و همچنین  مقدار صفر برای کمترین و بیشترین قیمت دریافت می شود

تشکر

**Comment by sfmqrb** [comment]
ممنون از بابت اطلاع رسانی
بررسی میکنیم

**Comment by sfmqrb** [comment]
ایراد از سمت ای پی ای خود بورسه

**Comment by sfmqrb** [comment]
@Glyphack میشه بست این ایشو رو به نظرم

**Comment by Glyphack** [comment]
ممنونم @sfmqrb

**Comment by mjdehghan** [comment]
سلام 
تشکر از پاسخگویی شما @sfmqrb 

یک مسئله دیگر اینکه

به عنوان نمونه برای سهم غکورش اطلاعات دریافت میشود

 سهام  در سابقه خود در سایت tse برای تاریخ 1400/11/08 برای فیلد اولین قیمت دارای مقدار هست

وقتی برای دریافت اطلاعات این سهم برنامه اگه بطور مستقل چندبار اجرا شود

در بیشتر اجراهای متوالی برای این تاریخ فقط مورد قیمت اولین خرید را برابر مقدار صفر می هد و مابقی اطلاعات به درستی اطلاعات دریافت شده

و  در میان اجراهای متوالی یک و دو مورد هم هم پیش میاد قیمت اولین خرید به درستی دریافت می شود و اطلاعات موردی ندارد

این مسئله هم به مسئله قبل مرتبط هست

تشکر

**Comment by Glyphack** [comment]
مرسی
چون خیلی زیاد این مشکلات پیش نمیاد فکر کنم بهترین روش برای فهمیدن مشکل این باشه که یه کدی اضافه کنیم به پکیج که زمانی که اینطور خطاها رخ داد یه گزارش کاملی از چیزی که از سایت بورس گرفته بهمون بده.
