### ISSUE TITLE
تابع get_stats مقدار مینیمم روز ندارد

### ISSUE THREAD

**Issue by alireza-solouk** [Glyphack/pytse-client#197]
سلام
تابع get_stat()
فکر کنم نام ستون DF در خروجی «قیمت ماکزیمم امروز» باشد و نه «ماکزیمم قیمت سال» (max_year)
یک بررسی بکن
با تشکر

**Comment by Glyphack** [comment]
ممنونم الان حضور ذهن ندارم ولی اگر این هست باید تغییر راحتی باشه انجامش. مرسی بابت اصلاح.
