### ISSUE TITLE
مشکل در دریافت اطلاعات حقیقی حقوقی

### ISSUE THREAD

**Issue by HMD911** [Glyphack/pytse-client#2]
**توضیح مشکل پیش آمده**
مشکل در دریافت اطلاعات خرید و فروش مشتری‌های حقیقی و حقوقی
ticker.client_types

**چطور اتفاق افتاد؟**
کاری که میکردم که باعث شد این اتفاق بیوفته:
1. اطلاعات یکی از سهم‌ها رو دانلود کردم
2. سعی داشتم  اطلاعات خرید و فروش مشتری‌های حقیقی و حقوقی رو بگیرم با دستور زیر
`ticker.client_types`
3. ارور زیر رو گرفتم

  File "C:\Users\؟؟؟\temp.py", line 5, in <module>
    print(ticker.client_types)  

  File "E:\ProgramData\Anaconda3\lib\site-packages\pytse_client\ticker.py", line 131, in client_types
    client_types_data_frame[f"{i}value"].astype(float) /

TypeError: 'NoneType' object is not subscriptable

**انتظار دارید چه اتفاقی بیوفته**
انتظار دارم با اجرای دستوری که گفتم، اطلاعات خرید و فروش مشتری های حقیقی و حقوقی را در روزهای مختلف به دست بیارم

**اطلاعات سیستم:**
 - سیستم عامل: ویندوز 7
 -  پایتون ورژن 3.7
 - از محیط اسپایدر آناکوندا استفاده می‌کنم

**Comment by Glyphack** [comment]
مرسی بابت گزارش. درست شد این مشکل

**Comment by HMD911** [comment]
بله متشکرم، درست شد.
مرسی از شما به خاطر این بسته‌ی عالی
