### ISSUE TITLE
نشناختن نماد کماسه

### ISSUE THREAD

**Issue by ebad84** [Glyphack/pytse-client#20]
**مشکل نشناختن برخی از دستورات در پایتون**

**چطور اتفاق افتاد؟**
کاری که میکردید که باعث شد این اتفاق بیوفته
طبق گفته های ویرگول پیشرفتم و کد هارو زدم در محیط پایچارم
اما 4-5 خط آخر رو بهم ارور داد و میگه همچین چیزی موجود نیست. مثلا این کد رو زدم : 
import pytse_client as tse

tse.download(symbols="کماسه", write_to_csv=True)  # optional
ticker = tse.Ticker("کماسه")
# print(ticker.history)  # سابقه قیمت سهم
#
# print(ticker.title)  # نام شرکت
#
# print(ticker.url)  # آدرس صفحه سهم
#
# print(ticker.group_name)  # نام گروه
#
# print(ticker.eps)  # eps
#
# print(ticker.p_e_ratio)  # P/E
#
# print(ticker.group_p_e_ratio)  # group P/E

print(ticker.base_volume)  # حجم مبنا

print(ticker.last_price)  # آخرین معامله

print(ticker.adj_close)  # قیمت پایانی

print(ticker.best_supply_price)  # قیمت بهترین تقاضا

print(ticker.best_supply_vol)  # حجم بهترین تقاضا

print(ticker.best_demand_price)  # قیمت بهترین عرضه

print(ticker.best_demand_vol)  # حجم بهترین عرضه
و این رو بهم برگردوند
375122.0
128720
127880
Traceback (most recent call last):
  File "C:/Users/Dr-raiane/Desktop/files_on_desktop_99 3 25/New folder/17 1 99/محمدرضا/kampozit/Projects/boooooooooooooors/1.py", line 25, in <module>
    print(ticker.best_supply_price)  # قیمت بهترین تقاضا
AttributeError: 'Ticker' object has no attribute 'best_supply_price'

**انتظار دارید چه اتفاقی بیوفته**
اطلاعات خواسته شده رو بهم برگردونه

**اطلاعات سیستم:**
 - سیستم عامل: ویندوز 10
 - ورژن پایتون : 3.7
 - محیطی که توش کار میکردید( سی ام دی، پاورشل یا بش) : پایچارم

**Comment by Glyphack** [comment]
سلام ورژن پکیج چند هست؟ باید این ورژن نصب شده باشه
`pip install pytse-client==0.5.1`

**Comment by AfcEagle** [comment]
با سلام
من یه مشکلی با این کتابخونه دارم
داخل پایتون همه چی خوبه و کار میکنه
من از پروژه فایل exe ساختم و وقتی اجرا میشه ارور زیر رو میده
  File "site-packages\pytse_client\symbols_data.py", line 12, in tickers_dict
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\uu\\AppData
\\Local\\Temp\\_MEI68922\\pytse_client/data/symbols_name.json'
این مسیر از بیخ ساخته نمیشه
pytse_client/data/symbols_name.json
نمیدونم چیکار کنم لطفا راهنمایی کنید بدجور گیرم

**Comment by thisismz** [comment]
با عرض سلام و خسته نباشید
من میخوام حجم فروش سهم ها رو داشته باشم از کد زیر استفاده می کنم اما هر کاری می کنم با خدای ایندکس مواجه میشم اگر امکانش باید راهنمایی بفرمایید با تشکر
`symbols = tse.symbols_data.all_symbols()
for symbol in symbols:
    ticker = tse.Ticker(symbol)
    print("namad :", symbol, "hajm:", ticker.best_supply_vol)`
list index out of range

**Comment by Glyphack** [comment]
@thisismz توی مثال ها یه نمونه کد هست برای این کار. اگر کار نکرد یک ایشوی جدید باز کنید
