### ISSUE TITLE
 اطلاعات فیلد ترازنامه

### ISSUE THREAD

**Issue by Glyphack** [Glyphack/pytse-client#201]
<p dir="rtl">

**مشکلی که دارید چی هست؟**
اطلاعات فیلد ترازنامه. قابلیت دانلود اطلاعات تاریخی از خود سایت هست.

<img width="1575" alt="image" src="https://github.com/Glyphack/pytse-client/assets/20788334/b8516dd2-4146-4ec9-bb91-2304e604193e">

</p>

**Comment by sfmqrb** [comment]
این فیلد آیا همیشه آپدیتن؟
کلا دیتاهای فاندامنتال tsetmc یادمه خیلی آپدیت نبود

**Comment by Glyphack** [comment]
راستش این رو نگاه نکردم یادمه پیشنهاد کس دیگه‌ای بود من ایشو رو درست کردم. خیلی هم اولویت نیست این با تغییراتی که توی سایت بورس دادن نشون داد خیلی قابل اعتماد نیست که چیزای زیادی از سایت بورس بخونی چون با یه تغییر همه چی میره رو هوا 😂

**Comment by Glyphack** [comment]
چون این بخش آپدیت نیست میبندم.
