### ISSUE TITLE
download share holder history

### ISSUE THREAD

**Issue by Amir80J** [Glyphack/pytse-client#208]
سلام ممنون از کد عالیتون
وقتی میخوام تاریخچه تغییرات سهامدارانو دان کنم برای هر سهم، حتما باید یه for  بنویسم که رو همه سهما ران بشه و بسیاز طولانیه روندش.
و وقتی هم به جای نوشتن اسم یک تک سهم برای سیمبل مینویسم 'all' کار نمیده که خودش همه رو دان کنه. میخواستم یه حرکتی بزنین که وقتی آل نوشتیم همش رو خودش دان کنه مثل بقیه دیتا ها.

**Comment by Glyphack** [comment]
سلام
تاریخچه سهامداران کلا عملیات کندی هست و دلیل اینکه اون امکان رو واسش نذاشتم این بود که سایت بورس بلاک میکرد همیشه وقتی اون تعداد ریکوئست میرفت. این مثالی که اینجا هست از تابع اسینک استفاده میکنه که میشه چندتا سهام رو همزمان دریافت کرد. اینو یه تست کنید نتیجه رو بگید که بهتر شد یا نه:

https://github.com/Glyphack/pytse-client/blob/master/pytse_client/examples/download_shareholders_history_aync.py

**Comment by Amir80J** [comment]
اره بهتر شد ممنون

**Comment by Glyphack** [comment]
من این ایشو رو میبندم اگر مشکل حل نشده دوباره بازش کنید
