### ISSUE TITLE
عدم بالا بودن سرویس

### ISSUE THREAD

**Issue by lordaltair** [Glyphack/pytse-client#210]
سلام وقت بخیر الان می خواهم داده های بورس رو دانلود کنم ولی سرویس دانلود نمیکنه و کلا کد گیر میکنه توی runtime، می خواستم بدونم مشکل از کجاست؟ سرویس بالا نیست؟ چون هیچ کاری انجام نمیده با تشکر
pytse-client و همه requirementsهاش هم همه اپدیت هستند

**Comment by Glyphack** [comment]
سلام فکر میکنم این به خاطر آپدیت‌های اخیر سایت باشه که ناپایدار شده.
https://github.com/Glyphack/pytse-client/issues/205

**Comment by sfmqrb** [comment]
@lordaltair 
هنوز این مشکل رو دارید؟

**Comment by Glyphack** [comment]
یه نفر توی ایمیل به من گفت که وقتی که تعداد سهام‌هایی که همزمان میگیره رو کم کرده این مشکل حل شده واسش. اگه همیشه درست کار بکنه این راه مشکل رو سرعت کم میشه ولی خطاها میاد پایین تر.
