### ISSUE TITLE
تاریخچه معاملات

### ISSUE THREAD

**Issue by amirali20002** [Glyphack/pytse-client#217]
سلامی دوباره
توی سابقه هر سهم تو سایت تی ای ایی که بریم، برای هر روز یک فیلم از معاملات داره.
میخواستم ببینم آیا امکانش هست که به اون دسترسی داشته باشیم ؟ برای تعداد و حجم معاملات هر لحظه بهش نیاز دارم.
یکی دیگه هم تو همین صفحه ریز معاملات هر روز اگر امکانش هست اضافه بشه

**Comment by Glyphack** [comment]
سلام این بخش ریزمعاملات تعداد و حجم رو میده:
https://github.com/Glyphack/pytse-client#%D8%B1%DB%8C%D8%B2-%D9%85%D8%B9%D8%A7%D9%85%D9%84%D8%A7%D8%AA-%D8%B3%D9%87%D8%A7%D9%85

اگر این کافی نیست با عکس بهتره نشون بدید که کجارو میخواید دقیقا.

**Comment by Amir80J** [comment]
برای هر نماد که بریم تو صفحه تی اس اییش اون بالا یه گزینه داره به اسم سابقه.
توی سابقه که بریم و یک تاریخی رو انتخاب کنیم، یه صفحه ای باز میشه که اون بالاش چنتا گزینه داره و یکیش معاملاته.
معاملات همون ریز معاملات هر روزه. اینی که الان داریم مال آخرین روز رو نشون میده

**Comment by Amir80J** [comment]
بعد تو همین قسمت سابقه نماد که میریم تو همون تب در یک نگاه دیتای لحظه ای سفارشات مثل یک فیلم قابل دسترسیه.
میخواستم ببینم به اون میشه اصن دسترسی داشت؟

**Comment by Glyphack** [comment]
آره اونم باید ازین طریق بشه گرفت
https://github.com/Glyphack/pytse-client#%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF-%D8%AA%D8%A7%D8%B1%DB%8C%D8%AE%DA%86%D9%87-orderbook

**Comment by sfmqrb** [comment]
https://github.com/Glyphack/pytse-client#%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF-%D8%AA%D8%A7%D8%B1%DB%8C%D8%AE%DA%86%D9%87-%D8%AC%D8%B2%D8%A6%DB%8C%D8%A7%D8%AA-%D9%85%D8%B9%D8%A7%D9%85%D9%84%D8%A7%D8%AA

@Amir80J 

با این تیک دیتای تاریخی و داده‌های کندلی تاریخی درون‌روزانه رو می‌تونید دریافت کنید

**Comment by sfmqrb** [comment]
@Glyphack 
البته گویا این ریلیز نشده نگاه کردم pypi رو

**Comment by sfmqrb** [comment]
به نظرم فیچر خیلی مهمیه یه ریلیز بدیم

**Comment by Glyphack** [comment]
راست میگی اشتباه کرده بودم. ورژن جدید میزنم الان.
@sfmqrb 
به خودت هم دسترسی میدم دیگه همه چیو بلدی اینجا 😃

**Comment by Amir80J** [comment]
ورژنشو جدید کردین؟

**Comment by sfmqrb** [comment]
آره ورژن 0.17

**Comment by Amir80J** [comment]
خیلی عالی ممنونم
فقط میخواستم بدونم آیا امکانش هست برای ریز معاملات هم به صورت تاریخی دیتا گرفت؟

https://github.com/Glyphack/pytse-client#%D8%B1%DB%8C%D8%B2-%D9%85%D8%B9%D8%A7%D9%85%D9%84%D8%A7%D8%AA-%D8%B3%D9%87%D8%A7%D9%85

یعنی همین دیتا به صورت تاریخی.
چون در دسترس هست توی تی اس ایی این دیتا به صورت تاریخی

**Comment by sfmqrb** [comment]
این تاریخیه ها :)

**Comment by sfmqrb** [comment]
عملا تیک دیتا تاریخی میشه ریز معاملات تاریخی

**Comment by Amir80J** [comment]
البته اره الان که فکرشو میکنم همونه 😁
