### ISSUE TITLE
کند بودن گرفتن ارزش معاملات

### ISSUE THREAD

**Issue by alirezazangi** [Glyphack/pytse-client#220]
<p dir="rtl">
**در حقله for سرعتش خیلی پایینه**
</p>

**Comment by Glyphack** [comment]
کدی که کند هست رو هم بذار

**Comment by sfmqrb** [comment]
به جای این کار میتونید از https://github.com/Glyphack/pytse-client#%D8%AA%D9%85%D8%A7%D9%85%DB%8C-%D8%A7%D8%B7%D9%84%D8%A7%D8%B9%D8%A7%D8%AA-%D9%85%D9%88%D8%AC%D9%88%D8%AF-%D8%A8%D8%B1%D8%A7%DB%8C-%D9%81%DB%8C%D9%84%D8%AA%D8%B1%D9%86%D9%88%DB%8C%D8%B3%DB%8C
استفاده کنید به مراتب سریع تره
@alirezazangi

**Comment by alirezazangi** [comment]
> 

خیلی ممنونم

**Comment by Glyphack** [comment]
فکر کنم این مشکل حل شده وگرنه بازش کنید.
