### ISSUE TITLE
دانلود نمیشه

### ISSUE THREAD

**Issue by hasanzad** [Glyphack/pytse-client#225]
در کد ساده زیر در حال حاضر ارور زیر را میده:

import numpy as np
import pandas as pd
import pytse_client as tse
df = tse.download(symbols='خودرو', write_to_csv=True)

Warning, download did not complete, re-run the code

**Comment by Glyphack** [comment]
مرسی نگاه میکنم

**Comment by Glyphack** [comment]
البته ممکنه در طول چند روز جواب ندم سعی میکنم تا هفته دیگه اینو با یه سری مشکل دیگه درست کنم.

**Comment by sfmqrb** [comment]
@hasanzad 
من تست کردم اوکی بود

**Comment by hasanzad** [comment]
@sfmqrb
کد من اشکالی توش نمیبینم پس چرا این ارور رو میده؟

**Comment by hasanzad** [comment]
دوستان اشکال از بنده بوده ظاهرا. دوباره pytse_clientرو اپگرید کردم درست شد. ورژن 17 الان نصب هست

**Comment by hasanzad** [comment]
دوستان اشکال از بنده بوده ظاهرا. دوباره pytse_clientرو اپگرید کردم درست شد. ورژن 17 الان نصب هست
