### ISSUE TITLE
tse.download()

### ISSUE THREAD

**Issue by amirali20002** [Glyphack/pytse-client#228]
قیمت تعدیل شده و قیمت تعدیل نشده در دانلود تاریخچه یکسان است.

![image](https://github.com/Glyphack/pytse-client/assets/107679897/ce721394-8372-43ad-8ca6-a14f07b055ac)

![image](https://github.com/Glyphack/pytse-client/assets/107679897/b222150c-3f9c-40b6-bc14-0ff6ce14df38)

**Comment by sfmqrb** [comment]
متوجه نمیشم
اینا که الان یکسان نیستن!

**Comment by amirali20002** [comment]
چرا دیگه قیمت تعدیل شده و نشده در آخرین روزو مثلا ببینین یکیه

**Comment by amirali20002** [comment]
هردوش ۵۲۹۰ ئه.
درحالی که تعدیل شده فولاد خیلی بیشتر از این حرفاست

**Comment by sfmqrb** [comment]
تعدیل قیمت روز آخر رو تغییر نمیده بلکه روزهای اول رو تغییر میده

**Comment by amirali20002** [comment]
اوو حق با شماست
ممنون
