### ISSUE TITLE
ایجاد قابلیت دریافت لحظه ای اطلاعات نماد های آپشن

### ISSUE THREAD

**Issue by MmdOjl** [Glyphack/pytse-client#229]
<p dir="rtl">
ماژول تیکر که به منظور دریافت اطلاعات لحظه ای نماد ها طراحی شده برای نماد های اختیار معامله جواب نمیده. فقط title و url نماد رو میشه با این ماژول دریافت کرد.

</p>

**Comment by sfmqrb** [comment]
یادمه تو ورژن های جدید با دادن ایندکس نماد اختیار این قابلیت رو اضافه کردیم

**Comment by MmdOjl** [comment]
![Screenshot 2023-10-16 141824](https://github.com/Glyphack/pytse-client/assets/32795239/e87e9626-13ad-4480-b87a-bec669bedc1b)
این خروجی ورژن آخره. دیتای تاریخی نمادای اختیار معامله رو میشه بدون مشکل دریافت کرد، ولی دسترسی به اطلاعات لحظه ایش از طریق ماژول Ticker وجود نداره.

**Comment by Glyphack** [comment]
من اون تایتل و ادرس رو توی این پی ار درستش کردم:
#223 

توی من قابلیت اینکه ما بقیه اطلاعات رو هم از سایت جدید بگیریم اضافه کردم ولی توی کلاس تیکر استفادشون نکردم. اگه وقت داشته باشی میشه شبیه کاری که بالا انجام شده رو برای بقیه متد ها انجام بدی.

**Comment by MmdOjl** [comment]
این پیکیج نمیدونم چرا اینشکلیه، رفتارش یکنواخت و قابل پیشبینی نیست. مثلا این خط کد رو یبار خطا میده و بلافاصله دفعه بعد جواب میده. 
![Screenshot 2023-10-19 180242](https://github.com/Glyphack/pytse-client/assets/32795239/d757e8e8-f3ac-4301-8348-af6d5c440212)
![Screenshot 2023-10-19 180540](https://github.com/Glyphack/pytse-client/assets/32795239/20096bbe-3987-4dbe-b55a-9ae106869355)

**Comment by Glyphack** [comment]
@MmdOjl
چون دیتا از سایت بورس میاد و اونا غیر قابل پیش‌بینی هستن. وقت داشته باشی میشه یه سری ارور مسیج‌های بهتری نوشت و اضافه کرد که توضیح بده ریترای کنی ارور رفع میشه.

**Comment by sfmqrb** [comment]
به نظرم  اینو تو لایه اپلیکیشن هندل کن که اگه ارور خوردی بعد یه مدتی retry کنه
اینا غیر قابل پیش بینی ان به تجربه من 
مثلا قبلا اینقدر که تو میگی این اتفاق نمی افتاد و احتمالا به عوامل مختلفی بستگی داره مثل نت و لوکیشن و ... 
و اینکه بخواد همچین چیزی تو خود لایبرری هندل بشه کار معقولی نیست 
تهش دیتا رو ما داریم از بورس می‌گیریم

@MmdOjl

**Comment by sfmqrb** [comment]
توی discord ما میتونی عضو شی اگه نیستی این پیام رو من از اون جا برای یه موضوع مشابه نوشتم و اینجا هم فرستادم

**Comment by MmdOjl** [comment]
سلام، تشکر بابت توضیحات شما. حقیقتش من در حد مبتدی  و خیلی شلخته کد میزنم، مثلا برای پیاده سازی بات تریدر شخصی. زیاد هم از گیت هاب سر در نمیارم. در هر حال اگر وقت شد یکمی بیشتر مطالعه میکنم. شاید تونستم برای بهبود این کتابخونه کمک کنم. 
@Glyphack 
@sfmqrb

**Comment by Glyphack** [comment]
کد شلخته هم بهتر از هیچیه میشه بهترش کرد. اگه خواستی این جارو بخون منم میتونم کمک کنم.
https://github.com/Glyphack/pytse-client/blob/master/CONTRIBUTING.md

**Comment by sfmqrb** [comment]
اینو ما اجرا میکنیم هیچی نمیگیریم
یعنی وارنینگ رو ریپرودیوس نمیتونیم بکنیم
ضخود8018 این رو اصلا ما نداریم تو symbol json
