### ISSUE TITLE
اضافه کردن تعداد و ارزش معاملات به شاخص های مالی

### ISSUE THREAD

**Issue by Mo-bakhtiari** [Glyphack/pytse-client#232]
<p dir="rtl">
سلام
تو اطلاعات شاخص های مالی جای دو کمیت مهم ارزش معاملات و تعداد معامات خالیه. بسیار عالی میشه اگر این دو مولفه هم اظافه بشه

</p>

**Comment by Glyphack** [comment]
سلام ممنون اضافه میشه. اینا اطلاعات کل معملات بازار هست یا تعداد معاملات یک سهم؟

**Comment by sfmqrb** [comment]
ارزش هستدالانم
tse.FinancialIndex(symbol="شاخص کل").last_value

**Comment by Mo-bakhtiari** [comment]
اینا اطلاعات کل سهم های دخیل در یک شاخص خاص هست. مثلا برای شاخص 50 شرکت برتر حجم و ارزش شاخص میشه مجموع حجم و ارزش معاملات این 50 شرکت. تو سابقه شاخص های مالی فقط سابقه ی حجم و عدد اون شاخص موجود هست. در خواستم این بود که سابقه ی تعداد معاملات و ارزش کل معاملات هم به خروجی اظافه بشه

**Comment by Mo-bakhtiari** [comment]
`tse.FinancialIndex(symbol="شاخص کل").last_value`
این اخرین مقدار عدد شاخص رو میده

**Comment by sfmqrb** [comment]
آره درست میگی شما

**Comment by sfmqrb** [comment]
این دیتا سورسش رو شما از کجای سایت بورس نگاه میندازی؟

**Comment by Mo-bakhtiari** [comment]
متاسفانه سایت بورس همچین اطلاعاتی نداره فقط امار روزانه رو نشون میده. ولی احتمالا این اطلاعات رو یه جا تو دیتابیسش ذخیره میکنه

**Comment by Glyphack** [comment]
اگر سورسی نداره بهترین کاری که پکیج میتونه بکنه اینه که دیتای روزانه رو بده و خودتون ذخیره کنید و بقیه چیزارو از روش بدست بیارید. چون اونم وجود داره من این ایشو رو میبندم اگر راه دیگه‌ای پیدا کردید برای اینکه تاریخچه رو بگیریم این رو باز کنید دوباره.

**Comment by Mo-bakhtiari** [comment]
اطلاعات به صورت اماده نیست اما قابل استخراجه. سهم های زیر مجوعه‌ی هر شاخصی مشخصه. مثلا سهم‌هایی که تو شاخص کل هستن لیستش موجوده و سابقه ی هر سهم هم موجود و قابل استخراجه. کاری که شما باید بکنی برای استخراج سابقه ی شاخص های مالی اینه که سابقه ی سهم های زیر مجموعه ی یک شاخص مالی رو باهم جمع کنید. مثلا برای شاخص 50  شرکت برتر مجموع تعداد معاملات و حجم و ارزش و خریدار حقیقی و ... این 50 شرکت مقادیر این کمیت ها را برای شاخص 50 شرکت به دست میده. حالا برای شاخص کل بورس یا فرابورس تعداد سهم ها یه مقدار زیاده که نیازه یه راه بهینه برای استخراج اطلاعات تک تک سهم ها و جمع کردنشون پیدا بشه و اگر محدودیت‌های سایت بورس این اجازه  رو نمیده حداقل با یه فانکشن غیر بهینه این امکان رو فراهم کنید. غیر بهینه بودن و زمان بر بودنش بهتر از نبودنش هست
