### ISSUE TITLE
پیدا نکردن تعدادی از نمادها

### ISSUE THREAD

**Issue by Airuop** [Glyphack/pytse-client#238]
سلام
 تعدادی از نماد ها  از طریق tse اطلاعاتش پیدا نمیشود.

برای مثال:
ticker = tse.Ticker("زفجر")
print(ticker.instrument_id)
خطا:
ValueError: Symbol زفجر not found, if you are trying to use
                             a symbol which is removed from the tse website
                             provide it's index manually:
                             ticker = tse.Ticker("", index="25165947991415904")

برخی از نمادهایی که این مشکل را دارند :

تفارس
کایزد
فزرین
وسالت
غمایه
تکیمیا
وآیند
بمولد
ثنور
حپرتو
نیان
ناما
گشان
زفجر
شهر
فن افزار
شستان
غدیس
درازی
فرود
گکوثر
ثقزوی
حاریا 
سلار
استقلال
وثخوز
تکاردان
عالیس
کتوسعه
والماس
وشمال

**Comment by Glyphack** [comment]
اگر نمادهایی که میخواید توی اون لیست جدید هست میتونید این رو ببندید

**Comment by Airuop** [comment]
> اگر نمادهایی که میخواید توی اون لیست جدید هست میتونید این رو ببندید

تفارس
وآیند

من با لیست جدید مقایسه کردم
این 2 نماد داخل آپدیت شما نبود
