### ISSUE TITLE
باگ روی گرفتن  دیتا نماد 

### ISSUE THREAD

**Issue by Airuop** [Glyphack/pytse-client#240]
سلام

روی گرفتن اطلاعات برخی از نماد ها باگ دارد و  خطای زیر نمایش داده میشود:
unsupported operand type(s) for *: 'NoneType' and 'float'

برای مثال tickers.p_e_ratio در  نماد (وآفری)

خطای

unsupported operand type(s) for *: 'NoneType' and 'float'

خیلی آزار دهنده  است در صورت امکان اگر پارامتری مقدار نداشت در پاسخ - برگرداند و همچین اروری ندهد.

با تشکر از شما 🙌

**Comment by sfmqrb** [comment]
ایراد از آپدیت نبودن جیسون symbols در دایرکتوری data هست.
باید با اسکریپت داخل دایرکتوری script آپدیتش کنیم (برای من خیلی کند بود یه تستش بکن لطفا شایگان)
خوبه اینو ما اتومیتش کنیم به عنوان یه تستی که هر روز انجام شه و دیفرنسش چک شه با آخرین ریلیز تا اگر فرقی بود pr بده. با github actions میشه همچین رول cron طوری رو تعریف کرد

@Glyphack

**Comment by sfmqrb** [comment]
https://github.com/Glyphack/pytse-client/pull/235
مشکل باید اینجا حل شده باشه

**Comment by Airuop** [comment]
> #235 مشکل باید اینجا حل شده باشه
سلام
لطفا برای انجام تست، ریلیز جدید بزارید.

**Comment by Glyphack** [comment]
امشب ریلیز رو انجام میدم فردا تست کنید.
