### ISSUE TITLE
سری زمانی  اطلاعات مربوط به eps, p/e, ...

### ISSUE THREAD

**Issue by farhadaz24511** [Glyphack/pytse-client#244]
با سلام
یک سوالی داشتم و آن این است که سری زمانی مثلا eps یا p/e را چطروی می تونم برای هر نماد بدست بیارم؟

**Comment by Glyphack** [comment]
سلام تا جایی که میدونم دیتای تاریخی p/e فقط لحظه‌ایش هست نمیشه تاریخه رو داشت باید جداگونه اضافه یشه.

**Comment by farhadaz24511** [comment]
> سلام تا جایی که میدونم دیتای تاریخی p/e فقط لحظه‌ایش هست نمیشه تاریخه رو داشت باید جداگونه اضافه یشه.

اگر که  اضافه بشود خیلی خوب خواهد بود ممنون از بانیاین این امر ا گر زحمتش را بکشند

**Comment by Glyphack** [comment]
این دیتا رو توی خود tse جایی نیست که آپدیت شده رو داشته باشه و باید از یه سورس دیگه خونده بشه. بنظرم از اسکوپ پکیج خارجه.
