### ISSUE TITLE
خطای دریافت اطلاعات

### ISSUE THREAD

**Issue by Airuop** [Glyphack/pytse-client#250]
سلام
 چند روزی هست خطای زیر باعث عدم دریافت اطلاعات میشود

HTTPConnectionPool(host='127.0.0.1', port=2334): Max retries exceeded with url: http://old.tsetmc.com/tsev2/data/Export-txt.aspx?t=i&a=1&b=0&i=34673681828119297 (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D503E97950>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))

**Comment by Glyphack** [comment]
سلام این بنظر محدودیت سایته که واسه شما پیش اومده آیپی رو عوض کنید درست میشه.

**Comment by Glyphack** [comment]
میتونی خودت ست کنی باید اعمال بشه:
https://stackoverflow.com/a/8287752/6183805

**Comment by Airuop** [comment]
> میتونی خودت ست کنی باید اعمال بشه: https://stackoverflow.com/a/8287752/6183805

پروکسی ایران که سالم باشه از کجا باید بهش اضافه کنم ؟
