### ISSUE TITLE
Time out error

### ISSUE THREAD

**Issue by hs15** [Glyphack/pytse-client#252]
Hi, I'm getting this warning when downloading a symbol data (i.e. `tse.download(symbols="وبملت", write_to_csv=True)`) and get stuck trying! Thanks!

`WARNING:urllib3.connectionpool:Retrying (Retry(total=3, connect=3, read=5, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x283db1d50>, 'Connection to old.tsetmc.com timed out. (connect timeout=10)')': /tsev2/data/Export-txt.aspx?t=i&a=1&b=0&i=17226661368470120`

**Comment by Glyphack** [comment]
timeout error => Website is down or unreachable by you. Cannot debug it further without your machine.
