### ISSUE TITLE
دانلود اطلاعات شاخص

### ISSUE THREAD

**Issue by kingtak66** [Glyphack/pytse-client#26]
با سلام
آیا روشی برای دانلود اطلاعات شاخص مانند:
... مقدار شاخص،حجم،ارزش معاملات و
که در صفحه اول سایت بورس در سمت راست نشون داده میشه دارید؟

**Comment by Glyphack** [comment]
سلام نه در حال حاضر این کار رو نمیشه با این پکیج انجام داد.
باید قابلیت خوندن شاخص اضافه بشه.

**Comment by kingtak66** [comment]
البته در سایت زیر فایل اکسل سابقه شاخص رو میشه گرفت.فقط مشکلش اینه با تاخیر میذارن و نمیشه بهش امیدوار  بود.
https://tse.ir/archive.html#/cash
اگه بتونید راه بهتری برای این کار پیدا کنید عالی میشه.

**Comment by sasai1363** [comment]
سلام
؟
![1](https://user-images.githubusercontent.com/25661491/95984963-d2a24100-0e30-11eb-9914-e5d18167d36e.jpg)

سهمی مثل دی را جستجو کنید خطا می دهد ، احتمالا به خاطر حرف ی است

**Comment by s-diaco** [comment]
[برنامه ای که خود سایت بورس درست کرده](https://cdn.tsetmc.com/Site.aspx?ParTree=111A11) 
دیتای به روز شده مربوط به شاخص‌ها رو از سایت 
tsetmc.com 
با فرمت سی اس وی می‌گیره. پس به نظرم باید بشه اینا رو گرفت ولی من نتونستم آدرس درست رو پیدا کنم.
اگر کسی که وارد هست بتونه یه نگاه به ریکوئست‌های شبکه بندازه (در زمانی که برنامه داره اطلاعات شاخص رو می‌گیره)، به نظرم یه کارایی می‌شه کرد.

**Comment by Glyphack** [comment]
<p dir="rt"> 
من یه بار این رو تگاه کردم ریکوئست‌هایی که می‌فرستاد xml بود و خیلی قابل فهمیدن نبود که چی به سایت میده
بنظر میاد این برنامه از یه سری api اختصاصی استفاده می‌کنه.
</p>

**Comment by HamidMousavi-git** [comment]
ب

> من یه بار این رو تگاه کردم ریکوئست‌هایی که می‌فرستاد خیلی قابل فهمیدن نبود که چی به سایت میده بنظر میاد این برنامه از یه سری api اختصاصی استفاده می‌کنه.

بله به نظر برنامه از وب سرویس سازمان بورس استفاده میکنه.خود وب سرویس هزینه اشتراک میخواد.
به نظر تنها چاره کار وب اسکراپینگ باشه.اونم پیچیدگی‌های خودشو داره.چون فقط دیتای اون روز قابل اسکراپ هست.یعنی اگه یه روز برنامه درست کار نکنه دیتای اون روز از دست میره

**Comment by Glyphack** [comment]
این اطلاعاتش روی صفحه شاخص هست خودم نگاه نکردم چقدر کار داشته باشه ولی بنظر پیچیدگی خاصی نداره اگر کسی خواست کمک بکنه میتونم راهنماییش کنم.

**Comment by mnoorchenar** [comment]
میشه راهنمایی بفرمایید اطلاعات شاخص رو چطوری میتونیم دریافت کنیم؟

**Comment by mnoorchenar** [comment]
> این اطلاعاتش روی صفحه شاخص هست خودم نگاه نکردم چقدر کار داشته باشه ولی بنظر پیچیدگی خاصی نداره اگر کسی خواست کمک بکنه میتونم راهنماییش کنم.

میشه راهنمایی بفرمایید چطوری میشه اینکارو انجام داد؟ لینک دریافت اطلاعات شاخص رو میشه بفرمایید؟

**Comment by Glyphack** [comment]
این صفحه شاخص کل هست برای بورس
http://www.tsetmc.com/Loader.aspx?ParTree=15131J&i=32097828799138957
توی این صفحه هم شاخص بقیه بازار های بورس هستن(تب بورس اوراق بهادار(
http://www.tsetmc.com/Loader.aspx?ParTree=15
این آدرس هم برای گرفتن دیتای خام شاخص هست
http://www.tsetmc.com/tsev2/chart/data/Index.aspx?i=5798407779416661&t=value
فقط روز و مقدار شاخص رو داره 
باید اطلاعات این صفحه رو گرفت و توی یک دیتافریم زخیره کرد.
اگر این یه تابع باشه و بشه روی  بقیه‌ی شاخص  ها هم  استفاده کرد خیلی حرفه‌ای خواهد بود.

**Comment by mnoorchenar** [comment]
تشکر ولی دیتا رو چک کردین؟ همین دیتای خام شاخص و ببینید همخوانی نداره با دیتای اصلی مثلا امروز رو زده
1400/4/16,327704.0
در صورتی که شاخص امروز
	1,282,036.10
بوده

**Comment by Glyphack** [comment]
آره چک کردم الانم چک کردم درست بود مقدارش
`1400/4/15,1281187.0;1400/4/16,1282036.1
`ممکنه زمانی که بازار باز هست این مشکل وجود داشته باشه باید یه روز که باز هست چک کنم این رو

**Comment by sfmqrb** [comment]
اگر این ایشو هنوز سالو نشده می تونم برم سراغش

**Comment by sfmqrb** [comment]
@Glyphack

**Comment by Glyphack** [comment]
@sfmqrb 
سلام نه هنوز روی این ایشو کاری نشده. اگر کمکی هم لازم بود من توی دییسکورد هستم.

**Comment by sfmqrb** [comment]
ممنون ازتون
