### ISSUE TITLE
عدم امکان دریافت داده ها به صورت حلقه

### ISSUE THREAD

**Issue by thisismz** [Glyphack/pytse-client#27]
با عرض سلام و خسته نباشید
من میخواستم حجم فروش رو در نماد ها به صورت تک به تک استخراج و سپس نمایش دهم
برای این کار توسط یک حلقه نام نماد ها رو یکی یکی به تیکر می فرستادم

symbols = tse.symbols_data.all_symbols()
for symbol in symbols:
     ticker = tse.Ticker(symbol)
     power_of_seller = ticker.best_supply_vol
     print("hajm:", power_of_seller)

اما هر سری بعد از اجرای چند خط با خطای زیر مواجه میشن که نمایش این خطا به صورت رندم هست شاید بعد از نمایش اطلاعات پنج سهم خودش رو نشون بده شاید هم همون ابتدای اجرا
![image](https://user-images.githubusercontent.com/25848626/93613630-5dd11800-f9e6-11ea-8d66-58d4df4f797a.png)

> in get_ticker_real_time_info_response
>     int(response.text.split()[1].split(",")[1]),
> ValueError: invalid literal for int() with base 10: 'F' 
مواجه شدم
البته بیشتر وقت ها با خطای زیر مواجه میشم
![image](https://user-images.githubusercontent.com/25848626/93612676-05e5e180-f9e5-11ea-9d85-3c834faf9c15.png)
![image](https://user-images.githubusercontent.com/25848626/93613695-72adab80-f9e6-11ea-8782-00c992340785.png)

**اطلاعات سیستم:**
 - سیستم عامل: مثل ویندوز ۱۰ 
 -3.7.6 ورژن پایتون
 - vscode
منمون میشم اگر راهنمایی بفرمایید
در نمونه مثال ها هم هچنین کدی با کاربرد مشابه نبود

**Comment by farhadmpr** [comment]
سلام
بنظرم باید خط 130 از فایل ticker.py بصورت زیر عوض بشه:

`int(float(response.text.split()[1].split(",")[1]))`

**Comment by Glyphack** [comment]
این کار رو کردم ولی مشکل دیگه‌ای اینجا وجود داره، ریسپانس این صفحه ممکنه عوض بشه هرچند بار که ریکوئست داده میشه
```
['12:29:59,A', ',35030,35920,36880,35130,36880,34410,1743,2694594,97013964340,0,20201004,122959;99/7/13', '16:40:06,F,1522937.56,<div', "class='mn'>(23217.06)</div>", '-1.5%,57275694292536300,14231448086,157052176902921,1530450,N,2246810881,40336737150586,559388,N,8938818,59681747958,4190,;5@3550@35300@35300@4390@3,4@1350@35020@35640@2000@1,6@4797@35000@35650@3280@2,;92511,588308,377679;2497523,197071,0,2559437,135157,861,2,0,629,2;;;0;']
```
و حالت دوم 
```
['06:37:52,IS,35180,36860,0,36860,0,0,0,0,0,0,20201004,63752;99/7/13', '16:40:06,F,1522937.56,<div', "class='mn'>(23217.06)</div>", '-1.5%,57275694292536300,14231447086,157052150412921,1530447,N,2246810881,40336737150586,559388,N,8938818,59681747958,4190,;;92486,594530,713329;;778253364357513@5420@5500@5610@28313@506130410@2783268952910,44818950263583523@44839@45327@47198@23398@61632348@2793580937643,28320293733348826@4100@4230@4220@45286@1126544017@4769330505430,63917421733088077@2980@2970@2840@36425@1262211133@3747961819160,33293588228706998@3780@3780@3600@7621@351757281@1328172042790,47302318535715632@4450@4470@4280@7168@221300342@988126633660,46830341954511303@26137@26137@25625@307@5949526@155502761062,9536587154100457@9800@9820@9770@4105@50267022@493828828100,24644999329120295@14051@14286@14349@2723@22192198@317041648624,7920014658832193@20000@19520@19908@1181@16626121@324541635678,41379697187196382@9392@9574@9583@37@300842@2825508064,45050389997905274@10900@11370@11240@2123@15489716@176187774320,47333458678352378@11600@11130@11430@1628@14600143@162435357150,38179358042686391@12200@11814@11814@0@0@0,22087269603540841@9990@9860@9860@0@0@0,19954896371640204@16183@16183@16857@85@1620159@26219033097,43913530989262989@9417@9638@9638@0@0@0,23175320865252772@4280@4156@4156@5@10200@43656000,20626178773287666@1000@1000@1000@0@0@0,47996917271187218@4630@4630@4630@0@0@0,49776615757150035@2088@2086@2086@0@0@0,7769065543658313@2716@2717@2717@0@0@0,7881099657101647@1000@1000@1000@0@0@0,41036181221659834@1000@1000@1000@0@0@0,20236748310756911@1000@1000@1000@0@0@0,71665987033532474@1000@1000@1000@0@0@0,49396161442874149@1000@1000@1000@0@0@0,70841787274602388@1000@1000@1000@0@0@0,57424362806755583@1000@1000@1000@0@0@0,34186024944625724@1213@2000@2000@0@0@0,;;3;']
```
 بنظر باید هردوتای این مدل ها درنظر گرفته بشه و ببینیم کدوم ریسپانس اومده و اون رو پارس کنیم

**Comment by Glyphack** [comment]
این مشکل رو حل کردم ورژن جدید
0.6.1
ازین به بعد مقدارهایی که وجود ندارند برابر
None
خواهند بود
