### ISSUE TITLE
مشکل دریافت اطلاعات حقیقی حقوقی

### ISSUE THREAD

**Issue by nela65** [Glyphack/pytse-client#28]
من برای گرفتن خروجی حقیقی و حقوقی مشلکل دارم فایلش دقیقا کدومه؟

یه دونه بود هر چی میزنم پیغام میده و رد میکنه

فایلی میخوام که با فرمت اکسل تمام حقیقی حقوقی رو بهم خروجی بده

میشه کمکم کنید اساتید

**Comment by nela65** [comment]
from pytse_client import download_client_types_records  
  
if __name__ == '__main__':  

  records_dict = download_client_types_records("all")
  print(records_dict["فولاد"])

اقای Glyphack 
میشه کمکم کنید این کد خطا میده واسم

**Comment by Glyphack** [comment]
فکر کنم پکیج نصب نشده. شده؟

**Comment by nela65** [comment]
wooooww
اره درست شد معرکه این مرسییییییییییییییییییییییییییییییییییییییییییی

فقط میشه این خروجی حقیقی و حقوقی و  هر 5 دقیقه به روز کرد اتومات و خودکار؟؟؟


 Glyphack بازم ممنونم ازتون اقای

**Comment by Glyphack** [comment]
خروجی حقیقی و حقوقی فعلا توی سایت بورس تهران روزانه به روز میشه و فایده‌ای نداره هر پنج دقیقه گرفتنش ولی میشه به
Ticker
خوندن اطلاعات حقیقی و حقوقی رو اضافه کرد تا بشه هر لحظه دیتا رو گرفت.
من این ایشو رو می‌بندم چون مشکل حل شده.

**Comment by nela65** [comment]
مرسی
میشه خواهش کنم کد شو برام یه بزرگی کنید بفرستید من یه اماتورم و واقعا بلد نیستم

گرفتن همین خروجی حقیقی حقوقی که هر 5 مین اطلاعات رو بده ؟؟

واقعا ممنون میشم اقای glyphack
