### ISSUE TITLE
عدم وجود اطلاعات دیروز و تغییرات درصدی و مقداری در سابقه

### ISSUE THREAD

**Issue by Judi89** [Glyphack/pytse-client#29]
در بخش سابقه اطلاعات دیگری مانند قیمت دیروز و تغییرات قیمتی و درصدی نیز وجود دارد ولی در این واکشی اطلاعات این قیمت ها نمی آید.
در خروجی که خود سایت تی اس سی نیز می دهد حداقل قیمت دیروز وجود دارد که می توان با توجه به آن درصد تغییرات را محاسبه کرد ولی در این واکشی شما نیست.
لطفا راهنمایی نمایید چگونه می تواند این اطلاعات را نیز واکشی کرد.

**Comment by Glyphack** [comment]
قیمت‌ها به ترتیب روز پشت سرهم هستن و قیمت دیروز میشه قیمت روز قبل که چون میشه بهش دسترسی داشت توی کد(مثلا اگر توی حلقه باشه) دیگه اون قیمت روز قبل توی هر روز نیست.

**Comment by Judi89** [comment]
اشتباهی که صورت گرفته اینست که در کد شما اولین قیمت به عنوان قیمت بازگشایی در نظر گرفته شده است در صورتی که قیمت بازگشایی قیمت پایانی دیروز است  و اولین قیمت، قیمت اولین معامله انجام شده است

**Comment by Judi89** [comment]
"<DTYYYYMMDD>": "date",
    **"<FIRST>": "open",**
    "<HIGH>": "high",
    "<LOW>": "low",
    "<LAST>": "close",
    "<VOL>": "volume",
    "<CLOSE>": "adjClose",
    "<OPENINT>": "count",
    "<VALUE>": "value"

در صورتیکه در فایل اکسل خود سایت  تی اس سی یک فیلد بنام 
[<OPEN>]
وجود دارد که قیمت پایانی دیروز می باشد

**Comment by Glyphack** [comment]
آره این فیلد توی دیتای خود سایت بورس تهران هست اما این عدد مقدار 
open 
نیست
مثلا توی این سایت‌ها قیمت باز که همون اوپن هست همون مقدار فرست هست
https://rahavard365.com/asset/167/trades
https://www.nahayatnegar.com/tv/IRO1IKCO0001
من فکر میکنم توی مفیدتریدر هم همین مقدار باشه. با این حساب مپینگ ما هم همین باشه کمتر باعث گیج شدن بقیه میشه.

**Comment by Judi89** [comment]
بهر حال آیا این امکان وجود داره که قیمت دیروز رو به این کد اضافه کنید و یا راهنمایی کنید که چه جوری می تونیم خودمون اضافه کنیم؟

**Comment by Glyphack** [comment]
آره 
دوتا درصد تغییر مختلف توی سایت یکی برای قیمت پایانی هست یکی هم برای آخرین قیمت. این دوتا با اسم های
close, adjClose 
توی دیتا هستن.
برای اینکه درصد تغییر رو بدست آورد مثلا برای روز آی اُم باید  تفاوت درصدی
i, i-1 
رو حساب کرد.

قیمت دیروز هم قیمت پایانی روز قبل هست پس برای گرفتن قیمت دیروز توی روز آی اُم باید قیمت پایانی روز 
i-1 
رو گرفت.

**Comment by Judi89** [comment]
بله، نحوه محاسبه رو می دونم، فقط تو این حجم از داده و برای هر روز رفتن و اطلاعات روز قبل رو هم بررسی کردن جهت محاسبه، کمی سرعت رو پایین میاره، منظورم این بود با توجه به اینکه اطلاعات قیمت دیروز در اکسل خود سایت تی اس سی در ردیف روز جاری هست، این امکان وجود داره که این فیلد رو مستقیم فراخوانی کنیم و دیگه نخوایم قیمت روز قبل رو از رکود روز قبل حساب کنیم

**Comment by Glyphack** [comment]
این نحوه کارکرد بهتره چون کل دیتا توی حافظه لود شده فکر نمیکنم تفاوت چندانی داشته باشه که از یه ستون دیگه دیتا رو بگیری یا از یک سطر دیگه.
جدا از این اگر توی یه تحلیل لازمه که تفاوت قیمت رو داشته باشید با خود
pandas
میشه که مثلا یه ستون 
diff
درست کرد با همون فرمول تفاوت قیمت امروز و دیروز محاسبه رو روی اون انجام داد.
