### ISSUE TITLE
 عدم وجود برخی نماد ها

### ISSUE THREAD

**Issue by Judi89** [Glyphack/pytse-client#30]
با سلام و احترام،
برخی نماد ها مثل انرژی 3 و یا نماد سفارود، وسپهر در این لیست واکشی وجود ندارند آیا دلیل خاصی دارد؟

**Comment by Glyphack** [comment]
سلام
نه قرار هست وجود داشته باشه این نمادها فقط مشکلی که بوده اینه که جایی برای گرفتن همه‌ی نمادهایی صحیح باشن توی سایت پیدا نکردم. جاهایی هست ولی مثلا نمادهایی که توشون دیتا نیست یا نمادهایی که دیگه فعالیت ندارن رو هم میزاره که باید یه طوری حذف بشه.
الان توی پکیج یه فایل هست که توش اسم و آیدی سهام ها هست و از روی اون سهام ها خونده میشن.
ولی برای اینکه یه سهامی که توی این لیست نیست رو بشه باهاش کار کرد یه قابلیت هست که میشه استفاده کرد
https://github.com/Glyphack/pytse-client/pull/14

**Comment by Judi89** [comment]
یعنی اینکه به این فایل 
JSON
آی دی نماد رو خودمون اضافه کنیم؟

**Comment by Judi89** [comment]
بنظر می رسه که نماد هایی که سال 99 وارد بورس شدن در این لیست نیست، لطفا راهنمایی نمایید چطور می توان این نماد ها را اضافه کرد؟

**Comment by Glyphack** [comment]
توی سایت آدرس نماد‌ها این شکلی هست
http://tsetmc.com/Loader.aspx?ParTree=151311&i=65883838195688438
عددی که اخر این ادرس هست آیدی سهامه که استفاده میشه بعد این نماد به این شکل توی فایل هست
https://github.com/Glyphack/pytse-client/blob/master/pytse_client/data/symbols_name.json#L511
برای اضافه کردن نماد جدید باید اسم نماد و اون آیدی توی فایل گذاشته بشه.

**Comment by Judi89** [comment]
ممنون

**Comment by Glyphack** [comment]
اگر لیست نماد‌هایی که توی پکیج نیست اینجا گذاشته بشه هم میشه به آپدیت جدید اضافشون کرد. تعدادشون زیاده؟

**Comment by Judi89** [comment]
من این فایل رو تکمیل کردم در ضمیمه ارسال می کنم


[symbols_name.zip](https://github.com/Glyphack/pytse-client/files/5380934/symbols_name.zip)

**Comment by Judi89** [comment]
حدود 50 نماد به این لیست اضافه شده است. از خط 631 به بعد

**Comment by Glyphack** [comment]
@Judi89 
میخوای با این یه پول ریکوئست بدی؟ بنظر دیتای خوبیه

**Comment by Mgavahi** [comment]
سلام من فایل جیسون رو کامل کردم و تمام نمادها رو اضافه کردم به این فایل ولی دیتای قبل رو دریافت میکنه یعنی دیتای همون نمادهای قبلی رو.
@Glyphack

**Comment by Glyphack** [comment]
سلام یک سری از نمادها از روی لیست دیده‌بان بازار و لیست نمادهای عادی بازار آپدیت شدند
