### ISSUE TITLE
امکان گروه بندی نماد ها

### ISSUE THREAD

**Issue by Judi89** [Glyphack/pytse-client#31]
با سلام و احترام،
چطور می توان نماد ها را طبق گروه دسته بندی کرد؟
با تشکر

**Comment by Glyphack** [comment]
میشه دید که یه نماد جزو چه گروهی هست از طریق پراپرتی
`group_name`
توی Ticker
https://github.com/Glyphack/pytse-client/blob/master/pytse_client/ticker.py#L63

**Comment by ashkanjalaliQ** [comment]
> با سلام و احترام،
> چطور می توان نماد ها را طبق گروه دسته بندی کرد؟
> با تشکر

میتونی با استفاده از فایل
`symbol_name.json`
و کمی زمان، همه نماد هارو گروه بندی کنی.
خیلی ساده یه حلقه میزنی که بره دونه دونه نماد هارو از فایل
`symbol_name.json`
بخونه و 
`group_name`
آن نماد رو توی یه فایل
`json`
یا
`csv`
ذخیره کنه...
امیدوارم تونسته باشم کمکت کنم

**Comment by rajabi-ali** [comment]
> میشه دید که یه نماد جزو چه گروهی هست از طریق پراپرتی
> `group_name`
> توی Ticker
> https://github.com/Glyphack/pytse-client/blob/master/pytse_client/ticker.py

**Comment by rajabi-ali** [comment]
با سلام- در خود صفحه هر نماد و در سایت گزینه ای برای اینکار وجود داره  که گروه بندی نماد ها توسط اون خیلی ساده انجام میشه

**Comment by Glyphack** [comment]
یعنی بشه مثلا اطلاعات حقیقی حقوقی یه گروه خاص رو دانلود کرد؟ @rajabi-ali

**Comment by rajabi-ali** [comment]
> یعنی بشه مثلا اطلاعات حقیقی حقوقی یه گروه خاص رو دانلود کرد؟ @rajabi-ali 
نه -ببینید عدد گروه برای هر سهم مشخصه-اگر همزمان با دانلود تیکر هر سهم این عدد رو کنار ستون ها گذاشت حتی اگر در خود پایتون فیلتر نویسی نکنیم-میشه در نرم افزار های تحلیلی بوری مثل آمی بروکرز این ستون رو وارد کرد(در کنار اطلاعات کندل ها) اونوقت میشه فهمید که ورود پول  یا خروج پول در چه گروه هایی بوده-به عبارتی فیلتر نویسی درون نرم افزار های تحلیل گر بورس با این گزینه میتونه روی گروه ها هم انجام بشه

**Comment by Glyphack** [comment]
جایی هست که همه‌ی گروه‌ها و نمادهاشون مشخص باشه؟ به جز صفحه دیدبان بازار ترجیحا @rajabi-ali

**Comment by rajabi-ali** [comment]
> جایی هست که همه‌ی گروه‌ها و نمادهاشون مشخص باشه؟ به جز صفحه دیدبان بازار ترجیحا @rajabi-ali

سلام-ببخشید دیر جواب دادم ایمیل هامو امروز چک کردم و پیامتون رو دیدم
چرا برای هر نماد اینو داریم
http://www.tsetmc.com/Loader.aspx?ParTree=151311&i=45728383369147894#
در تب شناسه هر سهم
این کد قرار داده شده

**Comment by Glyphack** [comment]
خیلی ممنون بنظرم کل اطلاعات این بخش شناسه باید اضافه بشه به برنامه که بشه بر اساس نام بازار یا نام گروه یا ... نام سهام هارو گرفت و استفاده کرد

**Comment by rajabi-ali** [comment]
> خیلی ممنون بنظرم کل اطلاعات این بخش شناسه باید اضافه بشه به برنامه که بشه بر اساس نام بازار یا نام گروه یا ... نام سهام هارو گرفت و استفاده کرد

معمولا نیازی نمیشه -در بخش فیلتر نویسی که انجام میشه فقط  اون کد گروه صنعت مهم هست و نه بقیه-مثلا اگر نیاز باشه ببینیم ورود پول 
 در چه گروهی بوده این کد رو که داشته باشیم به راحتی میشه برنامه و فیلتر رو نوشت  و فهمید کدوم گروه بیشترین ورود پول رو داشته یاچه تعدادی از هر گروه صنعت صف خرید یا فروش شدن و کارهای دیگه -همین یه عدد خیلی کار ها رو انجام میتونه بده

**Comment by sfmqrb** [comment]
این کد گروه صنعت به صورت یکجا در get_stats اضافه شده
ببندیم ایشو رو؟ @Glyphack
