### ISSUE TITLE
گزارش مشکل

### ISSUE THREAD

**Issue by mahshidTebyan** [Glyphack/pytse-client#34]
در دریافت اطلاعات مربوط به P/E برخی نمادها خطا ایجاد می شود
در اینجا یکی از نمادهایی که این خطا را داشت با کد توضیح دادم
1.اطلاعات مربوط به نماد "تپمپی" را دانلود کردم
        tse.download(symbols="تپمپی", write_to_csv=True)
2. سعی داشتم اطلاعات P/E رو بگیرم با دستورات زیر
        if symbols[s].ticker.p_e_ratio < symbols[s].ticker.group_p_e_ratio:
3. ارور زیر را گرفتم(متن کامل ارور)
    int(response.text.split()[1].split(",")[1]),
ValueError: invalid literal for int() with base 10: 'S'
مقدار response  هم پرینت گرفتم که این هست:
response: 06:37:52,IS,37240,37590,0,37590,0,0,0,0,0,0,20201019,63752;99/7/28 11:05:05,S,1467676.17,<div class='mn'>(46595.66)</div>,55780947218741690,1628636236,26467150292807,261440,S,634648932,12509526907866,223629,S,12053143,74690541540,2991,;0@0@0@37240@23960@13,0@0@0@39200@1500@2,0@0@0@40330@3458@3,;94015,604384,723305;;;;0;

**اطلاعات سیستم:**
 - سیستم عامل: مثل ویندوز ۱۰ 
 - 38: ورژن پایتون
 - محیطی که توش کار میکردید( pycharm)

**Comment by Glyphack** [comment]
سلام. توی این ریسپانس عدد پی به ای هست؟

**Comment by mahshidTebyan** [comment]
سلام
طبق این کد، از ریسپانس مقدار adj.close رو باید برداره که بله هست!

@property
def p_e_ratio(self) -> float:
    return self.get_ticker_real_time_info_response().adj_close / self.eps

**Comment by Glyphack** [comment]
این دوتا بهم مربوطند
https://github.com/Glyphack/pytse-client/issues/27
مشکل اینه که سایت ریسپانسی که میده هر چند ثانیه عوض میشه و وقتی عوض میشه ارور پیش میاد

**Comment by Glyphack** [comment]
این مشکل زمانی پیش میاد که پی به ای منفی باشه. ممکنه حالت های دیگه هم باشه ولی این یکی از دلایلش هست.

**Comment by Glyphack** [comment]
این مشکل رو حل کردم ورژن جدید
0.6.1
ازین به بعد مقدارهایی که وجود ندارند برابر
None
خواهند بود
