### ISSUE TITLE
دریافت برخط اطلاعات دیده بان روز

### ISSUE THREAD

**Issue by saeedsltm** [Glyphack/pytse-client#35]
سلام آیا امکانش هست که متدی افزوده بشه به جهت دریافت آنی اطلاعات دیده بان روز برای تمامی نمادها یا حداقل لیستی از اونها؟

**Comment by Glyphack** [comment]
بله قابلیت خوبیه.

**Comment by Glyphack** [comment]
سلام این امکان الان از طریق دیتای فیلترنویسی فراهم شده اگر بازم موردی هست بگید.
https://github.com/Glyphack/pytse-client#%D8%AA%D9%85%D8%A7%D9%85%DB%8C-%D8%A7%D8%B7%D9%84%D8%A7%D8%B9%D8%A7%D8%AA-%D9%85%D9%88%D8%AC%D9%88%D8%AF-%D8%A8%D8%B1%D8%A7%DB%8C-%D9%81%DB%8C%D9%84%D8%AA%D8%B1%D9%86%D9%88%DB%8C%D8%B3%DB%8C
