### ISSUE TITLE
گزارش مشکل

### ISSUE THREAD

**Issue by mostafa3053** [Glyphack/pytse-client#40]
سلام
برای گرفتن ticker.title 
از سهم انرژی3 مشکل داره! فکر میکنم درون کدها نوشتید که قسمت حروفی رو پیدا کنه و چون درون اسم این سهم عدد هم هست مشکل بوجود میاد!

**Comment by Glyphack** [comment]
سلام
مرسی که گزارش کردین.

**Comment by Glyphack** [comment]
سلام این مشکل اینجا حل شده
#47 
به ورژن 0.6.2 آپدیت کنید
