### ISSUE TITLE
گرفتن ناو صندوق‌ها

### ISSUE THREAD

**Issue by 5j9** [Glyphack/pytse-client#41]
<div dir=rtl>
برای صندوق‌های سرمایه‌گذاری مثل «دارا یکم» ظاهراً Ticker روشی برای گرفتن NAV ابطال نداره. اگر ممکن بود اضافه کنید.
</div>

**Comment by Glyphack** [comment]
سلام
آره در حال حاضر کل سهام‌هایی که میشه اطلاعاتشون رو گرفت توی فایل نوشته شدن. هنوز راه مناسبی برای اینکه چطوری اسم و کد سهم هارو توی اون فایل بشه جمع کرد(به صورت اتوماتیک) پیدا نکردم و به خاطر همین اون سهم ها اضافه نشده.

**Comment by sfmqrb** [comment]
این می تونه بسته شه @Glyphack
