### ISSUE TITLE
ارور numpy

### ISSUE THREAD

**Issue by zahedikhoozani** [Glyphack/pytse-client#48]
**توضیح مشکل پیش آمده**
با سلام. بنده نتونستم از پکیج استفاده کنم. خواستم مثال های خودتون رو اجرا کنم و متاسفانه با مشکل مواجه شدم.

**چطور اتفاق افتاد؟**
کاری که میکردید که باعث شد این اتفاق بیوفته:
1. اطلاعات همه سهام ها را دانلود کردم
با این کد مثال خودتون
"""
This example is about downloading all tickers csv data.
"""

from pytse_client.download import download

download(symbols="all", write_to_csv=True, base_path="hey")

2. ارور زیر را گرفتم(متن کامل ارور)

PS C:\Users\karim_wvzqrk5> python d:/pytse-client-master/pytse-client-master/pytse_client/examples/download_all.py
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "d:/pytse-client-master/pytse-client-master/pytse_client/examples/download_all.py", line 5, in <module>
    from pytse_client.download import download
  File "C:\Users\karim_wvzqrk5\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pytse_client\__init__.py", line 1, in <module>
    from .download import download
  File "C:\Users\karim_wvzqrk5\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pytse_client\download.py", line 6, in <module>
    import pandas as pd
  File "C:\Users\karim_wvzqrk5\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pandas\__init__.py", line 11, in <module>
    __import__(dependency)
  File "C:\Users\karim_wvzqrk5\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
  File "C:\Users\karim_wvzqrk5\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('C:\\Users\\karim_wvzqrk5\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86

**اسکرین شات**
![image](https://user-images.githubusercontent.com/39400389/98629035-3e42d580-232d-11eb-936b-1caf8a015c9b.png)

**اطلاعات سیستم:**
 - سیستم عامل: ویندوز ۱۰ 
 - python 3.8.6
 - محیطی که توش کار میکردید( سی ام دی، پاورشل یا بش)
windows powershell

**اطلاعات اضافی**
با تشکر

**Comment by ARFR2** [comment]
فکر می کنم مشکل از پکیج ها و دیپندنسی هاست از نصب کامل اون ها اطمینان حاصل کنید.

**Comment by Glyphack** [comment]
بنظر پکیج نامپای درست نصب نشده آخر ارور یه لینک هست من خوندم بنظر باگش هنوز فیکس نشده ولی این جواب رو تست کنید
https://developercommunity.visualstudio.com/solutions/1241964/view.html

**Comment by zahedikhoozani** [comment]
من ورژن پایتون رو عوض کردم به 3.9.0
به جای powershell هم از cmd استفاده کردم
الان ارور متفاوته
میگه No module named 'pytse_client'


C:\WINDOWS\system32>python C:\Users\karim_wvzqrk5\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytse_client\examples\download_all.py
Traceback (most recent call last):
  File "C:\Users\karim_wvzqrk5\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytse_client\examples\download_all.py", line 5, in <module>
    from pytse_client.download import download
ModuleNotFoundError: No module named 'pytse_client'


اما به نظرم پکیج رو درست نصب کردم
به اینصورت نصب شده:

C:\WINDOWS\system32>pip install pytse-client
Requirement already satisfied: pytse-client in c:\users\karim_wvzqrk5\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (0.6.1)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in c:\users\karim_wvzqrk5\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pytse-client) (2.24.0)
Requirement already satisfied: jdatetime<4.0.0,>=3.6.2 in c:\users\karim_wvzqrk5\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pytse-client) (3.6.2)
Requirement already satisfied: pandas in c:\users\karim_wvzqrk5\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pytse-client) (1.1.4)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\karim_wvzqrk5\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests<3.0.0,>=2.23.0->pytse-client) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\karim_wvzqrk5\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests<3.0.0,>=2.23.0->pytse-client) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\karim_wvzqrk5\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests<3.0.0,>=2.23.0->pytse-client) (2020.11.8)
Requirement already satisfied: idna<3,>=2.5 in c:\users\karim_wvzqrk5\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests<3.0.0,>=2.23.0->pytse-client) (2.10)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\karim_wvzqrk5\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pandas->pytse-client) (2.8.1)
Requirement already satisfied: numpy>=1.15.4 in c:\users\karim_wvzqrk5\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pandas->pytse-client) (1.19.4)
Requirement already satisfied: pytz>=2017.2 in c:\users\karim_wvzqrk5\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pandas->pytse-client) (2020.4)
Requirement already satisfied: six>=1.5 in c:\users\karim_wvzqrk5\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from python-dateutil>=2.7.3->pandas->pytse-client) (1.15.0)

**Comment by Glyphack** [comment]
بنظرم روی ورژن ۳.۶ هم تست کنید

**Comment by zahedikhoozani** [comment]
با ورژن 3.6.7 انجام شد
البته
numpy 1.19.4
مشکل داشت و 
numpy 1.19.3 
رو نصب کردم

با اینحال کماکان با پایتون 3.7 و پایتون 3.9 ارور دارم

https://stackoverflow.com/questions/64654805/how-do-you-fix-runtimeerror-package-fails-to-pass-a-sanity-check-for-numpy-an

**Comment by Glyphack** [comment]
مشکل به ورژن نامپای و پایتون مربوطه من این رو کلوز میکنم چون توی پروژه محدودیتی روی ورژن نامپای گذاشته نشده که باعث این بشه.
