### ISSUE TITLE
خطا برای نماد هایی که در فایل جیسون نیستند

### ISSUE THREAD

**Issue by zolanvar** [Glyphack/pytse-client#49]
سلام و خسته نباشید من یک مشکلی در کار کردن با این برنامه داشتم این بود که نماد هایی که در لیست جیسون نیستند برای بار اول برای دریافت سابقه معاملات و اطلاعات حقیقی حقوقی شون با خطا مواجه می شم ولی از دفعات بعد که کدش وارد اون لیست فایل جیسون می شه مشکلی نداره.

**Comment by Glyphack** [comment]
سلام.
مرسی این نباید ارور بده بار اول هم. البته بهترین حالت این هست که به جای فایل جیسون یه راه دیگه باشه که به همه‌ی سهام های سایت دسترسی داشته باشیم.

**Comment by alised** [comment]
@Glyphack  این هم مشکلش رفع شده است میتوانید ببندید اگر سهم داخل لیست نباشد خودکار اضافه می شود به لیست جیسون و بدون خطا دیتا را نمایش میدهد

**Comment by Glyphack** [comment]
مرسی
