### ISSUE TITLE
دریافت تمام پیشنهادهای خرید و فروش نماد

### ISSUE THREAD

**Issue by NaWeeDBHR** [Glyphack/pytse-client#50]
سلام امکانش هست قابلیت اضافه بشه کیفیت صف خرید و فروش بشه بررسی کرد مثل کارگزاری ها تا 5 تا بهترین پیشنهاد ها تعداد و حجم و قیمت نشون میدن توی تابلوشون

**Comment by Glyphack** [comment]
سلام آره
الان فقط بهترین خرید و فروش نشون داده میشه ولی میشه بیشتر کرد این رو که یک لیست باشه
