### ISSUE TITLE
گزارش مشکل

### ISSUE THREAD

**Issue by razieh-lab** [Glyphack/pytse-client#51]
سلام 
من کد اولیه رو هم که تویه colab مینوسم 
خطای time out میده 
pip install pytse-client
import pytse_client as tse
tickers = tse.download(symbols="ولملت")
tickers["ولملت"]

**Comment by Glyphack** [comment]
توی محیط کولب میشه به سایت بورس
www.tsetmc.com
دسترسی داشت؟

**Comment by razieh-lab** [comment]
شما کد رو تو محیط
colab
تست کردین؟
میشه لطف کنید تست کنید

**Comment by Glyphack** [comment]
نه من دسترسی ندارم به اون ولی این کد رو اجرا کنید ببینید نتیجه چی هست
```
import urllib.request
webUrl  = urllib.request.urlopen('http://tsetmc.com/')
print ("result code: " + str(webUrl.getcode()))
data = webUrl.read()
print (data)

**Comment by razieh-lab** [comment]
دوباره همون خطای 
time out 
رو میده 
در صورتی که به جای آدرس
tsetmc
آدرس
yahoofinance
رو میزنم خطا نمیده
:(((

**Comment by Glyphack** [comment]
بنظر میاد که سایت بورس قابل دسترسی نیست از اونجا. مشکل از سایته. این آدرس
چطور؟ http://en.tsetmc.com/Loader.aspx

**Comment by razieh-lab** [comment]
اینم همون خطا رو میده
TimeoutError                              Traceback (most recent call last)
/usr/lib/python3.6/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1324                 h.request(req.get_method(), req.selector, req.data, headers,
-> 1325                           encode_chunked=req.has_header('Transfer-encoding'))
   1326             except OSError as err: # timeout error

14 frames
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

URLError                                  Traceback (most recent call last)
/usr/lib/python3.6/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1325                           encode_chunked=req.has_header('Transfer-encoding'))
   1326             except OSError as err: # timeout error
-> 1327                 raise URLError(err)
   1328             r = h.getresponse()
   1329         except:

URLError: <urlopen error [Errno 110] Connection timed out>

**Comment by Glyphack** [comment]
شاید با پروکسی بشه دسترسی  داشت.

**Comment by razieh-lab** [comment]
امتحان کردم نشد:///

**Comment by zahragolpa** [comment]
منم همین مشکل رو دارم

**Comment by Glyphack** [comment]
این مشکل بنظر به خاطر این هست که توی کولب نمیشه به سایت بورس تهران دسترسی داشت نمیدونم چه راه حل هایی ممکن باشه.

**Comment by Glyphack** [comment]
فعلا این رو میبندم چون بنظر مشکل بخاطر کولب و سایت بورس هست راه فعلی اینه که اطلاعات رو دستی آپلود کرد مثلا ولی کار بهینه‌ای نیست.
