### ISSUE TITLE
دریافت ریزمعاملات روز جاری

### ISSUE THREAD

**Issue by wssq** [Glyphack/pytse-client#52]
با سلام
درصورت امکان ریز معاملات رو هم در این برنامه قرار دهید.
تشکر

**Comment by wssq** [comment]
برای مثال در آدرس زیر می توان ریز معاملات نماد وهنر راگرفت.
http://www.tsetmc.com/tsev2/data/TradeDetail.aspx?i=60783654574662426

که به صورت 
xml 
هست.
اگه بشه این مورد را اضافه کرد عالی میشه.

**Comment by Glyphack** [comment]
ممنون. پیشنهاد خیلی خوبی هست.

**Comment by sasai1363** [comment]
> برای مثال در آدرس زیر می توان ریز معاملات نماد وهنر راگرفت.
> http://www.tsetmc.com/tsev2/data/TradeDetail.aspx?i=60783654574662426
> 
> که به صورت
> xml
> هست.
> اگه بشه این مورد را اضافه کرد عالی میشه.



> برای مثال در آدرس زیر می توان ریز معاملات نماد وهنر راگرفت.
> http://www.tsetmc.com/tsev2/data/TradeDetail.aspx?i=60783654574662426
> 
> که به صورت
> xml
> هست.
> اگه بشه این مورد را اضافه کرد عالی میشه.

 سلام ببخشید این لینک برای ریز معاملات روز جاری هست از کجا بدست اوردین؟ایا لینکی برای ریزمعاملات روزهای قبل هم وجود داره ؟

**Comment by mnoorchenar** [comment]
وقت بخیر
این مورد اضافه شده 
خیلی اطلاعات مهم و مورد نیازی هست 
با تشکر

**Comment by Glyphack** [comment]
سلام هنوز اضافه نشده اضافه که بشه توی همین ایشو مینویسم.
کارایی که باید انجام بشه زیاد هست لیستش و من هم تقریبا یه نفری انجام میدم اینارو ممکنه طول بکشه اضافه شدنش اما سعی میکنم این زودتر اضافه بشه.

**Comment by mnoorchenar** [comment]
البته دوستمون اشتباه گفتن فکر کنم این لینک اطلاعات لحظه ای رو نشون میده برای هر نماد
http://tsetmc.com/tsev2/data/instinfodata.aspx?i=55127657985997520&c=44
شماره چهارم اگر با نقطه ویرگول جدا کنیم اطلاعات خرید حقیقی هاست
من اکی م اگر کمکی از دست م بر بیاد
این لینک لودش خیلی سبکه
فقط من نمیدونم باید چطوری کدشو بنویسیم چون خیلی مهمه در کمترین زمان ممکن بشه این اطلاعات رو اپدیت کرد اپدیت حداقل 5 الی نهایتا 10 ثانیه معقوله بیشتر از ااون شاید خیلی کاربردی نباشه
