### ISSUE TITLE
نحوه بروزرسانی دیتا

### ISSUE THREAD

**Issue by alisherafat01** [Glyphack/pytse-client#53]
سلام  دوستان . موقعی که دستور download رو میزنیم چجوری اطلاعات رو بروز میکنه؟ کلش رو میره از اول میگیره یا یه روال دیگه ای داره؟
بیشتر منظورم performance کار هستش 
این رو اگه توی صفحه اصلی هم بزارید خوبه فکر کنم سوال خیلیا باشه

**Comment by Glyphack** [comment]
موقعی که دانلود صدا بشه هر نمادی که اسمش توی دانلود باشه رو از اول از سایت میگیره
