### ISSUE TITLE
ایندکس بجای تاریخ

### ISSUE THREAD

**Issue by msngnj** [Glyphack/pytse-client#54]
باسلام
در تصویر اول، درخواست این نماد بدون دانلود هستش ، یعنی فقط تیکر صدا زده شده:
![Screenshot (888)](https://user-images.githubusercontent.com/26968366/103427118-ef4e4980-4bd3-11eb-99d2-08c3dc2186cb.png)

در تصویر دوم، ابتدا دانلود صدا زده شده ، سپس تیکر صدا زده شده :
![Screenshot (889)](https://user-images.githubusercontent.com/26968366/103427129-0b51eb00-4bd4-11eb-8f10-9ee55a212531.png)
حالا سوال اینجاست که چرا تو اولی تاریخ رو نشون میده و تو دومی شماره ردیف رو ؟ 
طریقه خوندن فایل CSV باید تغییر کنه ؟ 
با سپاس فراوان

IDLE V3.8.0 windows

**Comment by Shebeli** [comment]
سلام یه عکس از کدتون مربوط به عکسایی که گذاشتین قرار میدین؟

**Comment by alised** [comment]
@Glyphack فکر می کنم این مورد رفع شده باشد می توانید ببندید
