### ISSUE TITLE
دلیل نبود برخی اطلاعات

### ISSUE THREAD

**Issue by alisherafat01** [Glyphack/pytse-client#55]
برخی از اطلاعات تابلو در ماژول Ticker وجود نداره مثل موارد زیر:
وضعیت سهم(مجاز - متوقف و ...)
تابلوی سهم: تابلوی اول - بازار فرعی و ...
میانگین حجم
ارزش معاملات 
تعداد معاملات
اطلاعات حقیقی حقوقی روز جاری
و...
اینارو نمیشد گرفت و قرار داد توی Ticker? 
 اگه دلیل خاصی داشته بگید
تشکر...

**Comment by Glyphack** [comment]
سلام. اینا وجود نداشته چون من تعداد کمی رو فرصت کرده بودم از اون صفحه بگیرم و پیدا کنم. ولی دلیل خاصی نداشته

**Comment by alisherafat01** [comment]
من رفتم این دیتاها رو بگیرم مثلا وضعیت سهم که مجاز هست یا متوقف دیدم نیست توی سورس صفحه
ظاهرا از یه جایی دیگه داره پر میشه!
اطلاعی دارید در این خصوص که چجوری باید گرفت این فیلد رو

**Comment by alisherafat01** [comment]
خب یه کم تحقیقات کردم آدرس تعداد - حجم و ارزش معاملات روز رو متوجه شدم
http://tsetmc.ir/tsev2/data/instinfofast.aspx?i=114312662654155&c=56%20
ولی همچنان ارزش بازار رو پیدا نمیکنم!‍
