### ISSUE TITLE
امکان اجرای فیلترها

### ISSUE THREAD

**Issue by bhralzz** [Glyphack/pytse-client#56]
مکانیزمی برای اجرای فیلترهای  مشابه با فیلترهای دیده بان بازار
tsetmc 
وجود داره؟
یا حتما فیلترها باید اینور با زبان پایتون کدنویسی مجدد بشه؟

**Comment by Glyphack** [comment]
اون کدی که برای فیلترنویسی استفاده میشه اینجا ساپورت نمیشه. 
البته شاید بشه فیلتر رو برای سایت فرستاد و نتیجه رو گرفت اینطوری میشه ساپورتش کرد باید بررسی بشه

**Comment by sfmqrb** [comment]
فیلترنویسی و دریافت نتایج فیلتر یه پروسس کاملا لوکاله.
صرفا سایت دیتاهای مربوط به فیلتر رو برای کلاینت می فرسته و در کلاینت فیلترینگ انجام میشه.

**Comment by Glyphack** [comment]
من این ایشو رو درست کردم تا در آینده اطلاعاتی که صفحه فیلتر نویسی داره رو به پکیج اضافه کنیم. چون اون کار این ایشو رو یه جورایی حل میکنه این رو میبندم
#160
