### ISSUE TITLE
درخواست داده

### ISSUE THREAD

**Issue by maspak500** [Glyphack/pytse-client#59]
با سلام

برنامه ای که  نوشته اید بسیار جالب و حتما کاربردی است ، جای قدردانی دارد.

با توجه به عدم آشنایی من با زبان و محیط پایتون ،  آیا امکان دریافت نتایج  برنامه نوشته شده شما برای  سهام بازار بورس  بصورت فایل اکسل یا ...  هست ؟

با تشکر
مسعود

**Comment by Glyphack** [comment]
سلام بله امکان این کار هست توی این نمونه کد که نوشته شده میشه این اطلاعات رو دریافت کرد به شکل اکسل
https://github.com/Glyphack/pytse-client#%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF-%D8%B3%D8%A7%D8%A8%D9%82%D9%87-%D8%B3%D9%87%D9%85%D9%87%D8%A7
البته باید یه مقدار کم با نصب پایتون و اجرای دستور آشنا باشید

**Comment by maspak500** [comment]
ممنون ، تشکر
