### ISSUE TITLE
امکان دریافت شناوری؟

### ISSUE THREAD

**Issue by jalilimmd** [Glyphack/pytse-client#64]
با درود
سوالی داشتم در مورد این پروژه.

آیا امکان دریافت شناوری و حجم معاملات نماد ها به صورت روزانه با استفاده از این پروژه وجود داره یا نه؟

ممنون

**Comment by Glyphack** [comment]
<p dir="rtl">
میشه شناوری و حجم معاملات رو با عکس مشخص کنید کدوم بخش هست؟
</p>

**Comment by jalilimmd** [comment]
در سربرگ سهامداران هر نماد لیست سهامداران عمده نشان داده می شود.
شناوری هر نماد = مجموع درصد سهامداران عمده منهای ۱۰۰ درصد
![Screenshot_20210126_180905](https://user-images.githubusercontent.com/78023287/105859429-bf8f3780-6001-11eb-87fd-347230f141d8.png)


افزونه هایی برای مرورگر ها وجود دارد که این کار رو انجام میده. من میخوام این عدد رو برای تمامی نماد ها استخراج کنم.
مثل این:
![Screenshot_20210126_181327](https://user-images.githubusercontent.com/78023287/105859850-39272580-6002-11eb-94a8-d91f97f284fb.png)


و حجم معاملات هم که صفحه اول هر نماد نوشته
![Screenshot_20210126_182429](https://user-images.githubusercontent.com/78023287/105861342-db93d880-6003-11eb-99fd-51887ca9c98d.png)

**Comment by jalilimmd** [comment]
امکانش هست آیا ؟

**Comment by Glyphack** [comment]
آره این رو میشه اضافه کرد

**Comment by jalilimmd** [comment]
در صورت امکان اضافه شدن این مورد، میشه لطفا بگید حدودا چه زمانی این مورد رو اضافه می کنید ؟
چون خیلی به این نیاز دارم.
ممنون

**Comment by Glyphack** [comment]
هفته‌ی بعد اضافه میکنم

**Comment by Glyphack** [comment]
این مورد توی ورژن 0.7.0 اضافه شده و اینجا نحوه استفاده نوشته شده
https://github.com/Glyphack/pytse-client#%D8%B3%D9%87%D8%A7%D9%85%D8%AF%D8%A7%D8%B1%D8%A7%D9%86-%D8%B9%D9%85%D8%AF%D9%87

**Comment by jalilimmd** [comment]
بسیار ممنون و تشکر فراوان از توجه شما
