### ISSUE TITLE
 چه کدی چقدرخریده یا فروش داشته

### ISSUE THREAD

**Issue by sasan-saqaeeyan** [Glyphack/pytse-client#67]
با سلام امکانش است که در ریز معاملات متوجه شد که چه کدی چقدر خرید یا فروش داشته
مثلا می گن یک کد حقیقی چند میلیارد تومان خرید زد ؟ ایا شما می توانید کدها هنگام معاملات دسترسی داشته باشین ؟

**Comment by Glyphack** [comment]
سلام نه امکان دسترسی به کدها از سایت بورس موجود نیست فقط کل خرید و فروش حقیقی توی معاملات رو میشه دید. ریز معاملات هم فقط حجم معامله رو مشخص میکنه.
در کل راه مشخصی نداره کسایی که پیدا میکنن با بررسی چیزای مختلف این نتجیه رو میگیرن

**Comment by A5DkjGQUZx** [comment]
پیشنهاد میکنم تابع ii.ShowShareHolder در Loader.aspx را بررسی و مطالعه کنید
در آنجا کد یکتای سهامدار در TSETMC را کشف خواهید کرد که در همه نمادها از همان کد برای ارجاع به آن سهامدار استفاده میشود...
بسیار کاربردی است و کمتر شناخته شده است!

**Comment by sfmqrb** [comment]
> پیشنهاد میکنم تابع ii.ShowShareHolder در Loader.aspx را بررسی و مطالعه کنید در آنجا کد یکتای سهامدار در TSETMC را کشف خواهید کرد که در همه نمادها از همان کد برای ارجاع به آن سهامدار استفاده میشود... بسیار کاربردی است و کمتر شناخته شده است!

اینو می تونی بیشتر توضیح بدی یا مثلا یه مثال بزنی. اگر بتونی اسکرین شات هم بفرستی عالی میشه

**Comment by sasan-saqaeeyan** [comment]
> پیشنهاد میکنم تابع ii.ShowShareHolder در Loader.aspx را بررسی و مطالعه کنید در آنجا کد یکتای سهامدار در TSETMC را کشف خواهید کرد که در همه نمادها از همان کد برای ارجاع به آن سهامدار استفاده میشود... بسیار کاربردی است و کمتر شناخته شده است!

سلام و تشکر ، اگه امکانش هست توضیح بیشتر یا بقول دوستمون ییه اسکرین شات بفرستید .تشکر و سپاس

**Comment by alised** [comment]
@Glyphack نمایش کد سهامداران حقیقی که امکان پذیر نیست سهامداران عمده هم که تابع اش در کد وجود دارد.
اگر ممکن است یک نگاهی به بخش مشکلات بندازید و مواردی که رفع شده اند را ببندید.

**Comment by Glyphack** [comment]
مرسی @alised
