### ISSUE TITLE
سهامداران عمده

### ISSUE THREAD

**Issue by paysheen** [Glyphack/pytse-client#68]
تغییرات سهام داران عمده هم اگه اضافه بشه عالیه
اطلاعاتشم تو سایت tse هست

**Comment by Glyphack** [comment]
Related: #64

**Comment by Glyphack** [comment]
این مورد توی ورژن 0.7.0 اضافه شده و اینجا نحوه استفاده نوشته شده
https://github.com/Glyphack/pytse-client#%D8%B3%D9%87%D8%A7%D9%85%D8%AF%D8%A7%D8%B1%D8%A7%D9%86-%D8%B9%D9%85%D8%AF%D9%87
