### ISSUE TITLE
حدود هفتاد سهم جامانده و جدید

### ISSUE THREAD

**Issue by ashkankhalaj** [Glyphack/pytse-client#69]
سلام دوست عزیز
 من هنگام ران کردن متوجه شدم یک سری از نمادها تعریف نشده که با دیتا بیس خودم یه مقایسه کردم و متوجه شدم این ها هستند و تصمیم گرفتم برای تمیز تر شدن کارتون این لیست رو براتون بفرستم
آینده، تلیسه، کزغال، کماسه،  کدما، ومعادن، چخزر، کسرام، کاذر، کفپارس، ساذری، کباده، فاسمین، فاهواز، وسدید، فاذر، فلامی، فبستم، تپکو، تفیرو، تمحرکه، خزامیا، خفناور، قجام، قنقش، بکهنوج، خودکفا، غاذر، غشان، غدیس، غصینو، دحاوی، شسینا، دهدشت، کازرو، شگامرن، ممسنی، بوعلی، کحافظ، سبزوا، ستران، وکبهمن، وصنا، وملت، وکار، سمایه، انرژی1، انرژی2، انرژی3، نبورس، نکالا، سپیدار، های وب، شساخت، البرز،وسفارس، وسلرستا،وسخوز، وسصفا، وساغربی، وساشرقی، وسکرد، وسگیلا، وسرضوی، وسیزد، وسکرمان، وسهمدا، وسکهبو، وسیستا، وسمازن
در ضمن سهم آس پ هم که توی لیستتون هست بین الف و سین فاصله ای نداره میتونید بین سین و الف فاصله بزارید تا با نوشتار سایت تی اس ای یکی در بیاد 
بازم متشکر بابت کار ارزشمندی که انجام دادید

**Comment by Glyphack** [comment]
سلام خیلی ممنونم. اینارو اضافه میکنم.
