### ISSUE TITLE
ticker.client_types

### ISSUE THREAD

**Issue by garshasb-cyber** [Glyphack/pytse-client#7]
سلام.خسته نباشی.
امکانش هست تابعی برای ذخیره و دانلود اطلاعات حقیقی و حقوقی هم قراربدی؟
یه جوری که بشه هم بصورت تک به تک و هم همه سهام بصورت یکجا اطلاعات رو ذخیره کرد؟
.ممنون از لطف شما.متاسفانه من تازه وارد دنیای برنامه نویسی شدم والا به شما زحمت نمیدادم.

**Comment by Glyphack** [comment]
سلام بله ایده‌ی خوبی هست باید یه تابع واسه این کار مثل `download`  که اطلاعات معامله دانلود میشه وجود داشته باشه.

**Comment by garshasb-cyber** [comment]
خیلی هم عالی،بنظرم اگه وقت ازاد داشتین این پکیج رو توسعه بدین و امکان تحلیل تکنیکال و حتی استفاده از هوش مصنوعی رو هم بهش اضافه کنید.
به علت سرعت بالای گسترش بورس تو جامعه بنظرم با استقبال مواجه بشه.

ضمنا سرعت دانلود داده های سهام با برنامه شما خیلی بالاتر از برنامه خود سازمان بود.

**Comment by Glyphack** [comment]
ممنون در حال حاضر هدف این پکیج راه جامع و سریعی واسه گرفتن اطلاعات باشه. کار تحلیل جدا از این باید انجام بشه.

**Comment by Glyphack** [comment]
این قابلیت توی ورژن 0.6.0 اضافه شده.
مرسی از @mtndaghyani

**Comment by garshasb-cyber** [comment]
perfect.
عالی بود.دقیقا همون چیزی که نیاز داشتم.
ممنون از هر دو عزیز
