### ISSUE TITLE
گزارش مشکل

### ISSUE THREAD

**Issue by mojinumber1** [Glyphack/pytse-client#77]
سلام و خسته نباشید
هنگام کار با تابع دریافت اطلاعات سهامداران عمده و تشکیل حلقه به مشکل وجود نداشتن دیتا در بعضی نمادها بر خورد کردم همچنین در برخی نماد ها مثل بکام با این که نمادها در 
و  سایت بورس با حروف عربی نوشته میشوند اما با حرف ک فارسی و ی فارسی پاسخ دریافت میکرد و با نام اصلی خیر. برخی نمادها هم هنگام قرار گرفتن در حلقه خطا داشتند و از سمت سرور بعذ از ۵۰۰ تلاش پاسخ دریافت نشد. این مورد به نظر با گذاشتن دستور اسلیپ کمی برطرف شد اما سوال اینجاست. چرا زمانی که لیست نمادهایی که در خود برنامه تعریف شده موقع قرار گرفتن در حلقه و دریافت اطلاعات سهامداران عمده چنین ایرادی ندارد؟

خلاصه کد برنامه به این صورت است:
from pytse_client import Ticker
import pandas as pd
import time
pd.set_option('display.max_columns',20)

names = ["اپرداز","اتکام","اتکای",...]

a = 0

for x in names:
      print(Ticker(x).shareholders.percentage.sum())
      a = a + 1
      if (a == 25 or a == 50 or ... a == 625):
      time.sleep(10)

**Comment by Glyphack** [comment]
سلام فکر کنم این مشکل مربوط به سایت بوده و توی چیزایی که با شبکه کار دارن ممکنه پیش بیاد. بنظرم این هم نیاز به ریترای کردن داره اگر سایت بورس بعضی وقتا ۵۰۰ میده
