### ISSUE TITLE
مقايسه قسمت تعديل شده در نمادها

### ISSUE THREAD

**Issue by mohi021** [Glyphack/pytse-client#78]
سلام و ممنون از پكيج خوبت، اگه بشه بتونيم ستون خاصي از ديتا رو براي چند نماد با تاريخ فراخواني كنيم خيلي خوب ميشه، مثلا يه بازه اي از تاريخ رو براي چند نماد انتخاب كنبم و اون نمادا قيمتاي تعديل شدشو همراه تاريخ، باهم مقايسه كنه

**Comment by Glyphack** [comment]
سلام
این کار رو با دیتافریمی که برنامه میده میشه انجام داد. اگر سایت بورس قابلیت این رو میداد که بازه مشخص کنیم برای گرفتن دیتا این کار به صرفه بود ولی در هر صورت باید کل دیتا از سایت دانلود بشه و اینکه توی برنامه قابلیت فیلتر کردن داده بشه فایده‌ی زیادی نداره و خود کاربر میتونه فیلتری که میخواد رو روی دیتاها انجام بده

**Comment by Glyphack** [comment]
فکر کنم مشکل حل شده من این ایشو رو میبندم
