### ISSUE TITLE
خطا در دریافت تاریخ شمسی

### ISSUE THREAD

**Issue by Mgavahi** [Glyphack/pytse-client#79]
سلام
زمانی که ما دیتا رو به صورت فایل سی اس وی دانلود میکنم یه مشکلی که وجود داره اینه که داده های تاریخ ما وقتی شمسی هست روزهای اخر ماه هایی که ۳۱ روزه هست رو به صورت خالی میده و برای رفع این مساله چه باید بکنیم ؟
ممنون

**Comment by Glyphack** [comment]
من این رو نگاه کردم ولی نمیتونم موردی که گفتید رو پیدا کنم برای مثال این یک خط رو ببینید
```
424,2019-08-31,10081.0,10095.0,10060.0,10073.0,113342655311,11251966,794,10072.0,10095.0,1398-06-09
410,2019-09-22,10174.0,10179.0,10170.0,10175.0,421328508135,41406231,1572,10167.0,10175.0,1398-06-31
```
اینجا مشکلی با روزای ۳۱ ام نداریم.

**Comment by alised** [comment]
منم بررسی کردم مشکلی ندیدم خاطرتان باشد برخی سرورها مشکل داشتند و داده برخی روزهاش خالی بود ممکن است برای ایشون هم چنین اتفاقی افتاده باشد.
دوستمان که پیگیری نکرده اند دیگه مشمول گذر زمان می شود 😄
