### ISSUE TITLE
ticker.client_types doesn't work

### ISSUE THREAD

**Issue by Mili90** [Glyphack/pytse-client#8]
با سلام
اطلاعات حقیقی و حقوقی به درستی نشون داده نمیشه حتی با آپدیت پکیج هم مشکل برطرف نشد.

ارور زیر رو میده:

'Ticker' object has no attribute 'client_types'

ممنون

**Comment by Glyphack** [comment]
سلام من این دستور رو اجرا کردم طبق عکس زیر شما هم همین کار رو میکنید و ارور میگیرید؟
![image](https://user-images.githubusercontent.com/20788334/85826532-fd8d5a00-b799-11ea-9da1-cdbc49748d35.png)

**Comment by Mili90** [comment]
بله منم دقیقا همین دستور رو تو ژوپیتر نوتبوک اجرا میکنم ولی میگه این ماژول همچین اتریبیوتی نداره.
البته تو سیستم دیگه اجرا کردم مشکلی نداشت ولی تو سیستم خودم اجرا میکنم این ارور رو میده.

**Comment by Glyphack** [comment]
این مشکل فقط توی نت بوک پیش میاد؟

**Comment by Mili90** [comment]
من کلا با نوت بوک کار میکنم.حتی یه بار پکیج رو پاک کردم و دوباره نصب کردم بازم همون ارور رو میده.
ولی جالبه که تو سیستم دیگه این ارور رو نداشت.فقط تو سیستم خودم هست که این ارور رو میده.
جای دیگه هم با همین نوت بوک ران کردم.

**Comment by Mili90** [comment]
سلام مجدد
من پکیج رو پاک کردم و دوباره نصب کردم مشکلم برطرف شد.
ممنون
