### ISSUE TITLE
self.get_ticker_real_time_info_response().adj_close / self.eps  ZeroDivisionError: float division by zeroگزارش مشکل

### ISSUE THREAD

**Issue by sasai1363** [Glyphack/pytse-client#80]
**توضیح مشکل پیش آمده**
سلام
تو ماجول تیکر برای بدست اوردن 
p/e
ممکن که 
eps
صفر باشد باید چک شود
self.get_ticker_real_time_info_response().adj_close / self.eps  ZeroDivisionError: float division by zero

**Comment by Glyphack** [comment]
خیلی ممنون اصلاح میشه
