### ISSUE TITLE
قابلیت دریافت اطلاعات دریافت تاریخچه سهامداران

### ISSUE THREAD

**Issue by Glyphack** [Glyphack/pytse-client#83]
<p dir="rtl">

**مشکلی که دارید چی هست؟**
قابلیت دریافت اطلاعات دریافت تاریخچه سهامداران عمده امکان پذیر نیست

**راه حل**
میتونیم از این صفحه این اطلاعات رو دریافت کنیم و به برنامه اضافه کنیم
http://cdn.tsetmc.com/Loader.aspx?ParTree=15131P&i=4369934250728330&d=20210202

**نکات تکمیلی**
این اطلاعات باید به شکل دیتافریم در دسترس باشه
</p>

**Comment by shahspik** [comment]
خسته نباشی
یه سوال داشتم
چجوری میتونم بجای نماد از آی دی نماد استفاده کنم و اطلاعات بگیرم ؟
مثلا بجای 
ticker = Ticker("وبملت")
از آی دی اون 
778253364357513
استفاده کنم و اطلاعات نمادو بگیرم.
؟
تشکر

**Comment by Glyphack** [comment]
سلام این کار رو نمیشه انجام داد. برای سوالات هم میتونید توی سرور دیسکورد بپرسید
https://discord.gg/2DCnQXB7
