### ISSUE TITLE
داده های تعدیل شده سهام

### ISSUE THREAD

**Issue by Akbarianh** [Glyphack/pytse-client#84]
<p dir="rtl">

**مشکلی که دارید چی هست؟**
به داده های تعدیل شده برای تحلیل در پایتون نیاز است

**راه حل**
اگر یک نگاه به نرم افزار تی اس ای کلاینت خود سازمان ببیندازین و ابزاری دارین که ریکوئست ها را می تونین ببینین میشه سورس داده های تعدیل شده را بدست آورد

**نکات تکمیلی**
سلام من برنامه نویس هستم و پایتون کار می کنم البته نه خیلی حرفه ای . از پکیج شما استفاده کردم  ولی احتیاج به داده های تعدیل شده دارم اگر سورس این داده ها را با ابزارهایی که دارید پیدا کنید و به من بدهید من خودم اون قسمت برنامه دانلودش را می نویسم . فعلا مشکلم سورس داده های تعدیل شده است. اگر اطلاع دارید و به من بدید ممنون میشم.

</p>

**Comment by Glyphack** [comment]
مرسی. ابزاری که خود سازمان میده چی هست؟

**Comment by sasai1363** [comment]
سلام واقعا خسته نباشین برای کاری که  دارید انجام  میدهید ولی به نظرم تلاشتون بگذارید رو این موضوغ چون واقغا داده های تعدیل شده نباشن ارزشون برای تحلیل خیلی پایین می اید.........

**Comment by Akbarianh** [comment]
سلام نرم افزار 
TseClient 
را از خود سایت سازمان میشه دانلود کرد و هم اطلاعات تعدیل شده را میشه باهاش دانلود کرد و هم تعدیل نشده اما من می خوام از داخل خود نرم افزار بتونم دانلود کنم. نرم افزار  را می تونین گوگل کنین لینک دانلودش را بهتون میده

**Comment by Glyphack** [comment]
باشه من این رو روی ویندوز تست میکنم خبر میدم

**Comment by Glyphack** [comment]
<p dir="rtl">
من این رو چک کردم وقتی با برنامه دیتا رو دانلود میکنی این ریکوئست و ریسپانس رو میگیره.
اینجا از api soap استفاده شده و body ریکوئست هم encode شده و معلوم نیست که دقیقا چی هست
واسه استفاده از این api باید این بادی رو decode کرد که کار آسونی نیست و نیاز به رمزنگاری داره.
</p>
[Request.txt](https://github.com/Glyphack/pytse-client/files/6175117/Request.txt)
[Response.txt](https://github.com/Glyphack/pytse-client/files/6175118/Response.txt)

**Comment by Glyphack** [comment]
از سایت‌های دیگه‌ای برای تحلیل دیتای سهم‌هارو دارن جایی هست که دیتای تعدیل شده رو داشته باشه؟

**Comment by Akbarianh** [comment]
سلام ممنون که وقت گذاشتید. قصه داده های تعدیل شده یکم پیجیده است حتی داده هایی خود تی اس آی کلاینت سازمان بورس میده پر از نویز و داده های اشتباهه. از همین رو شرکتهای مختلف داده های تعدیل شده را آماده می کنند و با گرفتن آبونمان اجازه دانلود روزانه را به مشتریانشون میدهند. نکته دیگه اینکه هر کدوم از این شرکتها برای تبدیل داده های تعدیل نشده به تعدیل شده روش و الگوریتم خودشون را دارن لذا داده هاشون یکم با هم متفاوت است. . 3 تا شرکت که بیشترین مشتری را دارند . نوآوران امین http://www.nadpco.com/
رهاورد 365 rahavard365.com  و 
رهاورد نوین https://mabnadp.com/rahavardnovin3 
هستند ولی در تمام این شرکتها دادهای تعدیل شده را فقط در اختیار مشتریانشون می گذارند.بعضی هاشون حتی وب سرویس هم دارند و می تونین با خرید اشتراک از طریق وب سرویس این داده ها را بگیرید . مثل نوآوران امین. فکر می کنم خود سازمان هم وب سرویس برای اشتراک داشته باشه ولی مطمئن نیستم.

**Comment by Akbarianh** [comment]
من اشتراک رهاورد 365 را داشتم ولی تمام شده . اگر اشتراک جدید گرفتم از این شر کتها نمونه داده های دانلود شده را بهتون میدم . ولی همه این شرکتها هم برای دانلود داده ها از یک نرم افزار استفاده می کنند مثل خود سازمان بورس که تی اس ای کلاینت را داره.

**Comment by sasan-saqaeeyan** [comment]
سلام ،نمودار قیمتها بایستی پس از سود نقدی، افزایش سهام  تعدیل شوند
برای تعدیل نمودار قیمت یک سهم بعد از سود نقدی، میزان سود نقدی سهام را از آخرین قیمت سهم قبل از سود نقدی کسر می کنیم. سپس عدد بدست آمده را بر قیمت سهم قبل از سود نقدی، تقسیم می کنیم. نتیجه این معادله، یک ضریب است. این ضریب را ضربدر همه قیمت های قبل از سود نقدی می کنیم. بدین ترتیب، همه قیمتهای قبل از سود نقدی، تعدیل می شوند.

قیمت پایانی قبل از تقسیم سود نقدی / (سود نقدی تصویب شده – قیمت پایانی قبل از تصویب سود نقدی) = ضریب تعدیل بعد از تقسیم سود نقدی
منبع:https://boursetime.com/12836/adjusted-price-chart/

![sood](https://user-images.githubusercontent.com/25661491/114908043-f0c51a00-9e30-11eb-9c97-072ef42c0112.png)

 خوب ما با وب اسکرپینگ اطلاعات صفحه بالا را می خونیم، تاریخ های سود بدست می اوریم و بامحاسبه  اختلاف دو عدد  قبل و بعد تعدیل، سود تقسیم شده را بدست می اوریم حال همه پارامترها برای محاسبه ضریب را داریم واون را بر روی قیمت های قبل از تقسیم سود اعمال می کنیم

:خوب برای تعدیل قیمت های مربوط افزایش سرمایه
جهت تعدیل قیمت های قبل از افزایش سرمایه بایستی قیمت تئوریک سهم بعد از افزایش سرمایه را بدست آوریم و سپس بر آخرین قیمت پایانی قبل از افزایش سرمایه تقسیم کنیم 
تا ضریب تعیین بدست آید. حال کافی است تا تمام قیمتهای قبلی در نمودار را ضربدر این ضریب کنیم.
در زیر برای سهم مربوط به شبندر به قسمت اطلاعات تکمیلی  وافزایش سرمایه می رویم
![afzayesh_sarmaye](https://user-images.githubusercontent.com/25661491/114906857-bb6bfc80-9e2f-11eb-8182-c8975986a394.png)

با این فرمول های بالا به نظرم قابل انجام است که داده تعدیل بشود
 ولی یه سوال که ذهنم درگیر کرده اینه که روز بعد گشایش بدون دامنه باز میشه و ممکنه 100 درصد هم رشد داشته باشه کاری دیگه باهاش نداریم.؟

**Comment by rajabi-ali** [comment]
> از سایت‌های دیگه‌ای برای تحلیل دیتای سهم‌هارو دارن جایی هست که دیتای تعدیل شده رو داشته باشه؟



> مرسی. ابزاری که خود سازمان میده چی هست؟

با سلام من برای انکار غیر از پیشنهاد دوستمون که در بالا گفته شد و بسیار کار بردی هست یه راه دیگه هم به نظرم میرسه
