### ISSUE TITLE
قابلیت گرفتن اطلاعات سهام در فایل اکسل

### ISSUE THREAD

**Issue by Glyphack** [Glyphack/pytse-client#91]
<p dir="rtl">

**مشکلی که دارید چی هست؟**
قابلیت گرفتن اطلاعات سهام در فایل اکسل
**راه حل**
همه‌ی دیتایی که از طریق Ticker میشه گرفت رو بشه به شکل csv هم دریافت کرد
**نکات تکمیلی**

</p>

**Comment by mojemadi** [comment]
سلام
بله سوالم این هست که چطور میتونم مثلا تمام درصدهای شناوری رو برای تمام سهام در فایل اکسل با نام نماد داشته باشم
با ماژول Ticker 
میشه پرینت کرد برای تک تک سهام.
اما من دنبال این هستم که برای تمام نمادها یک فایل سی اس وی
csv
داشته باشم با میزان درصد شناوری

به مثال زیر توجه بفرمایید 
import pytse_client as tse

tse.download(symbols="ذوب", write_to_csv=True)  # optional
ticker = tse.Ticker("ذوب")
print(ticker.shareholders.percentage.sum())
print(100 - ticker.shareholders.percentage.sum())

الان من فقط تونستم درصد شناوری نماد ذوب رو پرینت کنم اما میخوام اولا
1-این درصد رو در فایل اکسل یا سی اس وی  داشته باشم
2-بتونم در یک فایل تمام درصدهای شناوری  و نام نماد و اگر هم بشه تعداد کل سهام آن نماد
نمونه فایل اکسل یا سی اس وی
تعداد سهام      |   درصد شناوری      |نام نماد   |

**Comment by rajabi-ali** [comment]
سلام

**Comment by Glyphack** [comment]
چون این کار خیلی میتونه به انواع مختلفی انجام بشه من چیزی که متوجه شدم رو اینجا مینویسم:
- یک تابع وجود داشته باشه که تمام اطلاعات تاریخی یک سهام رو به شکل یک دیتافریم بده(که به اکسل هم تبدیل میشه)‌ اینا میشه شامل تمام سوابقی که میشه از Ticker گرفت
- یک تابع وجود داشته باشه که تمام اطلاعات لحظه‌ای سهام رو در قالب دیتافریم بده
حال زمانی که این دوتا تابع وجود داره و میشه برای هر سهم این رو جدا گرفت با خود pandas خیلی راحت هست ترکیب کردن این csv ها که یک csv واحد برای کل دیتا داشته باشیم.

**Comment by Glyphack** [comment]
تابع اول، این تابع اطلاعات تاریخی سهام رو با یک ستون تاریخ برمیگردونه که میشه شامل:
اطلاعات قیمت-سهامداران عمده- اطلاعات فیلترنویسی
```
get_ticker_histroy(ticker: Ticker)
```

تابع دوم، این تمام اطلاعات لحظه‌ای سهام رو به همراه نام نماد برمیگردونه:
اطلاعات تابلو - اطلاعات لحظه‌ای قیمت - درخواست‌های خرید و فروش-
```
get_ticker_real_time_info(ticker: Ticker)
```

خروجی این دوتا تابع دیتافریم(csv)هست و میشه این توابع رو برای سهام‌های مختلف صدا کرد و اونارو با هم ادغام کرد. میشه برای این قسمت سوم هم یک تابع آماده گذاشت که کد کمتری لازم باشه نوشته بشه.

**Comment by Glyphack** [comment]
سلام این دو مورد در ورژن ۰.۱۴.۰ اضافه شدند.
