### ISSUE TITLE
پیشنهادی برای پکیج بورس

### ISSUE THREAD

**Issue by BehrouzJ-68** [Glyphack/pytse-client#92]
<p dir="rtl">

**مشکلی که دارید چی هست؟**
اطلاعات لحظه ای حقیقی و حقوقی از طریق این پکیج در دسترس نیست

**راه حل**
از بخش دیده بان سایت تی اس ای میشه به اطلاعات لحظه ای دسترسی داشت. با استفاده از کدهایی که خود سایت برای فیلتر نویسی تعبیه کرده است.

**نکات تکمیلی**

</p>

**Comment by Glyphack** [comment]
سلام اطلاعات حقیقی و حقوقی لحظه‌ای رو میشه هم از طریق Ticker و هم از طریق دیدبان بازار گرفت(مورد دوم بزودی اضافه میشه). 
https://github.com/Glyphack/pytse-client/issues/160
