### ISSUE TITLE
تاریخچه‌ی ارزش بازار و تعداد سهام

### ISSUE THREAD

**Issue by mjavadshamsi** [Glyphack/pytse-client#98]
<p dir="rtl">

سلام،
اول، متشکرم از زحمتی که کشیدید برای پکیج عالی‌تون
دوم، آیا قابلیت دریافت ارزش بازار و یا تعداد سهام وجود داره؟
ممنونم

</p>

**Comment by Glyphack** [comment]
<div dir="rtl">
سلام
میشه با عکس نشون بدید که تعداد سهام رو کجا میشه دید؟
ارزش بازار هم به زودی اضافه میشه
</div>

**Comment by mjavadshamsi** [comment]
![image](https://user-images.githubusercontent.com/28251924/117028241-6d8f3980-acf5-11eb-8920-94076dcf007b.png)

البته یکی‌ش هم باشه تا حد خوبی کفایت می‌کنه، چون که قیمت*تعداد سهام همون ارزش بازار رو می‌ده.

**Comment by Glyphack** [comment]
مرسی این رو اضافه میکنم.

**Comment by mjavadshamsi** [comment]
خیلی خیلی ممنونم.

**Comment by Glyphack** [comment]
تعداد سهام رو میشه از طریق تابع
total_shares
گرفت.

**Comment by mjavadshamsi** [comment]
خیلی ممنونم. عالی. فکر کنم باید آپگرید می‌کردم چون برای من این
attribute
رو نداشت.

تنها نکته اینه که تعداد سهام در طول زمان ممکنه تغییر کنه اما این روش فقط آخرین تعداد سهام رو میده.

**Comment by Glyphack** [comment]
آره اون مورد هم هست.

این ایشو رو باز بذاریم برای ارزش بازار و یک ایشوی جدید درست میکنم برای تاریخچه‌ی تعداد سهام

**Comment by Glyphack** [comment]
سلام @nela65 
این ایشو مربوط به گرفتن ارزش بازار هست برای اطلاعات لحظه‌ای خرید و فروش حقیق و حقوقی این ایشو هست
https://github.com/Glyphack/pytse-client/issues/99
لطفا اونجا اگر موضوعی هست مطرح کنید این قابلیت هنوز اضافه نشده

**Comment by Glyphack** [comment]
این آدرس دیتای تعداد سهام رو برای هر روز داره
http://cdn.tsetmc.com/api/Instrument/GetInstrumentHistory/71483646978964608/20220828
