### ISSUE TITLE
امکان اضافه کردن تعداد و حجم فروش و خرید حقیقی و حقوقی لحظه ای

### ISSUE THREAD

**Issue by abcdamir2** [Glyphack/pytse-client#99]
<p dir="rtl">

**امکان اضافه کردن تعداد و حجم فروش و خرید حقیقی و حقوقی لحظه ای**
 با سلام و عرض احترام از انجا که شما در پکیجتون امکان قیمت لحظه ای رو گذاشتید در صورت امکان تعداد و حجم خرید و فروش حقیقی و حقوقی رو میشه گذاشت ؟
  این داده ها خیلی به تابلو خوانی کمک میکنه  و اطلاعات مفیدی رو میده

**راه حل**
میتونیم از این صفحه هر نماد در قسمت در یک نگاه این اطلاعات رو دریافت کنیم و به برنامه اضافه کنیم
![1](https://user-images.githubusercontent.com/30677591/119219407-b23f1100-bafa-11eb-899d-bb97aee15d28.png)

**نکات تکمیلی**
البته شما در قسمتی اونهاررو گذاشتید تایم فریم روزانه است که پایان هر روز اضافه میشه اگه بشه در لحظه یعنی تایم فریم خود بازار داشته باشیم میشه اطلاعات مفیدی در همون موقع گرفته بشه.

 با تشکر از شما
</p>

**Comment by Glyphack** [comment]
سلام ممنون بابت پیشنهاد قرار داده میشه.

**Comment by na3r** [comment]
سلام
ممنون بابت زحماتی که کشیدید برای این لایبرری
روی این ایشو تونستید وقت بزارید؟

**Comment by Glyphack** [comment]
سلام این یه پول ریکوئست باز داره اون مرج بشه اضافه میشه
